import { createHash } from 'node:crypto'
import type { Plugin } from 'vite'

/**
 * Emits the service worker, with the build's own asset list baked in.
 *
 * The worker is generated rather than written by hand because the thing it must
 * precache is a list of HASHED filenames that only exists after the bundle is
 * written — `index-D1Nb5fAh.js` is a different file every build. A hand-written
 * worker would either hard-code names that go stale on the next build (and then
 * serve a 404 from cache, which is worse than no worker) or fetch a manifest at
 * runtime, which cannot work when the whole point is the network being gone.
 *
 * No workbox. The repo's runtime dependencies are react and zod, and what is
 * needed here is roughly forty lines of cache API — small enough that reading
 * it is cheaper than reading a configuration surface that generates it.
 */
export function serviceWorkerPlugin(): Plugin {
  return {
    name: 'strange-chess:service-worker',
    // Build only. In dev there is no bundle to precache and a worker holding a
    // stale cache in front of the dev server is a debugging trap.
    apply: 'build',
    generateBundle(_options, bundle) {
      const assets = Object.keys(bundle)
        .map((f) => `/${f}`)
        .sort()
      // Everything the app needs with the network gone. `/` is listed because a
      // navigation request asks for the URL, not for `index.html`.
    // `public/` is copied outside the Rollup bundle, so `...assets` never
      // contains an icon — every one has to be listed by hand, and the maskable
      // variant was missed on the first pass while the manifest declared it.
      const precache = [
        '/',
        '/manifest.webmanifest',
        '/icons/icon-192.png',
        '/icons/icon-512.png',
        '/icons/icon-512-maskable.png',
        ...assets,
      ]
      // The cache NAME carries the build's identity. Without that the new
      // worker writes into the old cache and the update is invisible; with it,
      // activate can delete every cache that is not this build's.
      const version = createHash('sha256').update(precache.join('\n')).digest('hex').slice(0, 12)
      this.emitFile({ type: 'asset', fileName: 'sw.js', source: source(precache, version) })
    },
  }
}

function source(precache: string[], version: string): string {
  return `/* Generated by vite-plugin-sw.ts — do not edit. Build ${version}. */
const CACHE = 'strange-chess-${version}'
const PRECACHE = ${JSON.stringify(precache, null, 2)}

self.addEventListener('install', (event) => {
  // No skipWaiting here on purpose. A worker that activates immediately
  // replaces the running app under a player mid-match; this one waits until
  // the page asks, which is what the update prompt is for.
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)))
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      for (const key of await caches.keys()) {
        if (key !== CACHE) await caches.delete(key)
      }
      // Take control of pages that loaded before this worker existed, so the
      // FIRST visit is already covered rather than the second.
      await self.clients.claim()
    })(),
  )
})

self.addEventListener('message', (event) => {
  // The only way this worker activates early: the page asked, because a person
  // pressed the update button.
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting()
})

self.addEventListener('fetch', (event) => {
  const request = event.request
  if (request.method !== 'GET') return
  const url = new URL(request.url)
  if (url.origin !== self.location.origin) return

  // A navigation asks for a URL this app does not have a file for — it is a
  // single page. Serve the shell, from the network when it is there so a new
  // build is picked up, from the cache when it is not.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          // waitUntil, not a floating promise. \`respondWith\` extends this
          // worker's life only until the response settles, so an un-awaited
          // cache write can be cut off when the browser suspends the worker —
          // and browsers that reclaim workers aggressively are exactly the ones
          // this app ships to. The visible result is a shell that silently
          // never refreshes.
          event.waitUntil(caches.open(CACHE).then((cache) => cache.put('/', response.clone())))
          return response
        })
        .catch(async () => (await caches.match('/')) ?? Response.error()),
    )
    return
  }

  // Everything else is hashed, so a hit is always the right bytes and there is
  // no reason to ask the network first.
  //
  // Matched by URL STRING, not by the Request. A reload marks every request it
  // starts with cache mode 'reload', and matching such a Request against the
  // cache misses — so the app came back from a reload with its shell served and
  // both of its assets failing, which looks exactly like a precache that never
  // ran. It had run; the lookup was the wrong shape. The URL is the identity
  // that matters here anyway: these filenames carry a content hash.
  event.respondWith(
    caches.match(url.pathname + url.search).then((hit) => {
      if (hit) return hit
      return fetch(request).then((response) => {
        if (response.ok && response.type === 'basic') {
          // Same lifetime rule as the navigate branch above.
          event.waitUntil(caches.open(CACHE).then((cache) => cache.put(url.pathname + url.search, response.clone())))
        }
        return response
      })
    }),
  )
})
`
}
