/**
 * Legacy 12x12 source sprites retained for the generator and its tests.
 *
 * Runtime UI art is now imported from `src/ui/art/assets/` as high-resolution
 * WebP images. This module is no longer imported by the application renderer;
 * it remains only because the legacy candidate generator and its invariant tests
 * still use the source sheet as historical authoring data.
 *
 * The WebP catalogue is the runtime source of truth. These rows are not emitted
 * by the bundler or precached by the service worker.
 *
 * **Characters.** `.` is transparent, `$` takes the caller's tint, and every
 * other character indexes `PIXEL_PALETTE`. An unknown character is drawn in
 * magenta rather than skipped — a missing colour should be loud in review, not
 * a hole in a king's crown.
 */

/** One sprite: exactly 12 rows of exactly 12 characters. `pixels.test.ts` pins both. */
export type PixelSprite = readonly string[]

/**
 * The shared ramp. Deliberately small and reused across all 41 sprites — a
 * per-sprite colour would make the sheet look like 41 unrelated drawings, and
 * the whole point of a sheet is that a bomb and a crown read as the same world.
 */
export const PIXEL_PALETTE: Readonly<Record<string, string>> = {
  o: '#0e0f14', // outline — every sprite is drawn against it
  s: '#9aa2b4',
  S: '#d5dbe6',
  w: '#7a4f22',
  // Lightened from the mock's #a9713a, which is 3.04:1 against the raised panel
  // a card face sits on — just under the 3.30:1 floor. Two sprites (the snare
  // and the recall) are mostly this tone and were the ones that failed.
  W: '#b87c40',
  K: '#23262f',
  H: '#5b6273',
  y: '#ffb23a',
  Y: '#ffd98a',
  P: '#7b52c9',
  c: '#c9a4ff',
  B: '#2a4fa8',
  b: '#8ab4ff',
  G: '#e0a52c',
  g: '#ffe089',
  C: '#7fe3ff',
  R: '#a72a1c',
  r: '#e8ded0',
  n: '#5b8f3e',
  N: '#86bd63',
  e: '#e83a1f',
  E: '#ff9b86',
  d: '#4a3b2a',
  D: '#6f5839',
}

/**
 * What a `$` cell becomes when the caller names no tint.
 *
 * A custom property with a literal fallback, not a bare colour. ADR-021 keeps
 * every colour in `tokens.css` so a re-skin is a data change, and a sprite drawn
 * on an untinted surface has to obey that too — but jsdom and a bare
 * screenshot have no stylesheet, and a sprite that renders invisible under test
 * is worse than one that names a default. The fallback is the theme's own value.
 */
export const DEFAULT_TINT = 'var(--pix-tint, #8ab4ff)'

export const PIXEL_SPRITES = {
  /* Pieces. `$` cells take the side tint — ADR-007 asks the two armies to differ
 * by more than hue, and the outline plus the fill do that at 12px. */
  'king': [
    '............',
    '.oo......oo.',
    '.oGo.oo.oGo.',
    '.oGooGGooGo.',
    '.oGGGGGGGGo.',
    '.oGGGGGGGGo.',
    '.oGGgGGgGGo.',
    '.oGGGGGGGGo.',
    '.oooooooooo.',
    '.o$$$$$$$$o.',
    '.o$$$$$$$$o.',
    '.oooooooooo.',
  ],
  'queen': [
    '.o...oo...o.',
    '.oo..oo..oo.',
    '.o$o.$$.o$o.',
    '.o$oo$$oo$o.',
    '.o$$$$$$$$o.',
    '.o$$$$$$$$o.',
    '..o$$$$$$o..',
    '..o$$$$$$o..',
    '.o$$$$$$$$o.',
    '.o$$$$$$$$o.',
    '.oooooooooo.',
    '............',
  ],
  'rook': [
    '............',
    '.oooooooooo.',
    '.o$$o$$o$$o.',
    '.o$$o$$o$$o.',
    '.o$$$$$$$$o.',
    '..o$$$$$$o..',
    '..o$$$$$$o..',
    '..o$$$$$$o..',
    '.o$$$$$$$$o.',
    '.o$$$$$$$$o.',
    '.oooooooooo.',
    '............',
  ],
  'knight': [
    '.....ooo....',
    '....o$$$o...',
    '...o$$$$$o..',
    '..o$o$$$$o..',
    '.oo$$$$$$o..',
    'o$$$$$$$$o..',
    'o$$oo$$$$o..',
    'oo..o$$$$o..',
    '....o$$$$o..',
    '...o$$$$$$o.',
    '..o$$$$$$$$o',
    '..oooooooooo',
  ],
  'bishop': [
    '.....o......',
    '....o$o.....',
    '...o$$$o....',
    '....o$o.....',
    '.....o......',
    '...ooooo....',
    '..o$$$$$o...',
    '..o$$$$$o...',
    '.o$$$$$$$o..',
    '.o$$$$$$$o..',
    '.ooooooooo..',
    '............',
  ],
  'pawn': [
    '.....oo.....',
    '....o$$o....',
    '....o$$o....',
    '.....oo.....',
    '....o$$o....',
    '...o$$$$o...',
    '...o$$$$o...',
    '..o$$$$$$o..',
    '.o$$$$$$$$o.',
    '.o$$$$$$$$o.',
    '.oooooooooo.',
    '............',
  ],
  'archer': [
    '...oo.......',
    '..o$$o......',
    '.o$$o.o.....',
    '.o$o...o....',
    '.o$o....o...',
    'o$$o..oSSSSo',
    'o$$o..oSSSSo',
    '.o$o....o...',
    '.o$o...o....',
    '.o$$o.o.....',
    '..o$$o......',
    '...oo.......',
  ],
  /* Special square types. */
  'bomb': [
    '.........o..',
    '........os..',
    '.......oso..',
    '....oo.so...',
    '...oKKo.....',
    '..oKHKKo....',
    '.oKHKKKKo...',
    '.oKKKKKKo...',
    '.oKKKKKKo...',
    '..oKKKKo....',
    '...oooo.....',
    '............',
  ],
  'portal': [
    '...oooooo...',
    '..oPPPPPPo..',
    '.oPPccccPPo.',
    '.oPcc..ccPo.',
    '.oPc....cPo.',
    '.oPc....cPo.',
    '.oPc....cPo.',
    '.oPcc..ccPo.',
    '.oPPccccPPo.',
    '..oPPPPPPo..',
    '...oooooo...',
    '............',
  ],
  'shrine': [
    '.oooooooooo.',
    '.oRRRRRRRRo.',
    '..oRRRRRRo..',
    '...oooooo...',
    '...oRoooRo..',
    '...oRoooRo..',
    '...oRoooRo..',
    '...oRoooRo..',
    '...oRoooRo..',
    '..oRRooRRo..',
    '.oRRRooRRRo.',
    '.oooooooooo.',
  ],
  'sanctuary': [
    '..oooooooo..',
    '.oBBBBBBBBo.',
    '.oBbbbbbbBo.',
    '.oBbBBBBbBo.',
    '.oBbBbbBbBo.',
    '.oBbBbbBbBo.',
    '.oBbBBBBbBo.',
    '..oBbbbbBo..',
    '...oBBBBo...',
    '....oBBo....',
    '.....oo.....',
    '............',
  ],
  'mire': [
    '.....oo.....',
    '....o$$o....',
    '...o$oo$o...',
    '...o$..$o...',
    '....oo$o....',
    '......$o....',
    '.o....$o..o.',
    'o$o...$o.o$o',
    'o$$oooooo$$o',
    '.o$$$$$$$$o.',
    '..oooooooo..',
    '............',
  ],
  /* Rule cards. */
  'hill': [
    '............',
    '.....oo.....',
    '....oSSo....',
    '...oSSSSo...',
    '..oSSggSSo..',
    '.oSSgddgSSo.',
    '.oSggddggSo.',
    'oSggdddggSo.',
    'oSgddddddgSo',
    'oggddddddgSo',
    '.oooooooooo.',
    '............',
  ],
  'three': [
    '..oooooo....',
    '.oGGGGGGo...',
    '.oGooooGo...',
    '.oo....oGo..',
    '......oGGo..',
    '....ooGGo...',
    '....oGGo....',
    '.oo...oGGo..',
    '.oGo...oGo..',
    '.oGGooooGGo.',
    '..oGGGGGGo..',
    '...oooooo...',
  ],
  'skull': [
    '...oooooo...',
    '..oSSSSSSo..',
    '.oSSooooSSo.',
    '.oSoSooSoSo.',
    '.oSSooooSSo.',
    '.oSSSooSSSo.',
    '..oSoooooo..',
    '...oSSSSo...',
    '..oSoSoSoSo.',
    '..oSoSoSoSo.',
    '...oooooo...',
    '............',
  ],
  'upgrade': [
    '.....oo.....',
    '....oYYo....',
    '...oYYYYo...',
    '..oYYYYYYo..',
    '.oYYYYYYYYo.',
    'oooooYYooooo',
    '....oYYo....',
    '.....oo.....',
    '..oooooooo..',
    '.oYYYYYYYYo.',
    '.oYYYYYYYYo.',
    '..oooooooo..',
  ],
  'crest': [
    '..oooooooo..',
    '.oBBBBBBBBo.',
    '.oBGGGGGGBo.',
    '.oBGoooooBo.',
    '.oBGoGGoGBo.',
    '.oBGoGGoGBo.',
    '.oBGoooooBo.',
    '..oBGGGGBo..',
    '...oBBBBo...',
    '....oBBo....',
    '.....oo.....',
    '............',
  ],
  'flame': [
    '.....oo.....',
    '....oyyo....',
    '...oyeeyo...',
    '..oyeEEeyo..',
    '..oeEyyEeo..',
    '.oyeEyyEeyo.',
    '.oyeEEEEeyo.',
    '.oyeeEEeeyo.',
    '..oyeeeeyo..',
    '..ooyyyyoo..',
    '...oooooo...',
    '............',
  ],
  'ranks': [
    '....oo..oo..',
    '...o$$oo$$o.',
    '...o$$oo$$o.',
    '....oooooo..',
    '...o$$oo$$o.',
    '..o$$$oo$$$o',
    '..o$$$oo$$$o',
    '.o$$$$oo$$$o',
    '.o$$$$oo$$$o',
    '.o$$$$oo$$$o',
    '.oooooooooo.',
    '............',
  ],
  // --- v12 card marks (same reason as the square marks below) ---

  /** Two bars: held, not gone. */
  'recoil': [
    '............',
    '..oooo.oooo.',
    '.oYYYYoYYYYo',
    '.oYYYYoYYYYo',
    '.oYYYYoYYYYo',
    '.oYYYYoYYYYo',
    '.oYYYYoYYYYo',
    '.oYYYYoYYYYo',
    '.oYYYYoYYYYo',
    '.oooo..oooo.',
    '............',
    '............',
  ],
  /** Three of the many, standing on one floor. */
  'democracy': [
    '............',
    '..o...o...o.',
    '.oYo.oYo.oYo',
    '.oYo.oYo.oYo',
    '.oYo.oYo.oYo',
    '.ooo.ooo.ooo',
    '............',
    '.oooooooooo.',
    'oSSSSSSSSSSo',
    '.oooooooooo.',
    '............',
    '............',
  ],

  // --- v12 square marks (PLAN-movement-lock-8x8-and-rule-cards Phase 5) ---
  // Drawn rather than taken from the spare pool: `art-key.test.ts` requires a
  // surplus per surface to SURVIVE a feature, and three square records would
  // have eaten it down from 10 to 7. A surplus the next feature eats is not one.

  /** A plank with a leap above it. */
  'springboard': [
    '.....oo.....',
    '....oCCo....',
    '...oCCCCo...',
    '..oCCCCCCo..',
    '.oCCoCCoCCo.',
    '.ooo.CC.ooo.',
    '.....CC.....',
    '....oCCo....',
    '.oooooooooo.',
    'oSSSSSSSSSSo',
    '.oooooooooo.',
    '............',
  ],
  /** A muster banner on its pole. */
  'levy': [
    '..o.........',
    '..oooooooo..',
    '..oGGGGGGo..',
    '..oGgggggo..',
    '..oGGGGGGo..',
    '..oGgggggo..',
    '..oooooooo..',
    '..o.........',
    '..o.........',
    '.ooo........',
    'oSSSo.......',
    '.ooo........',
  ],
  /** A stone block under a small flame. */
  'altar': [
    '.....oo.....',
    '....oeeo....',
    '...oeEEeo...',
    '....oeeo....',
    '.....oo.....',
    '.oooooooooo.',
    'oHHHHHHHHHHo',
    'oHssssssssHo',
    'oHHHHHHHHHHo',
    '.oHHHHHHHHo.',
    '.oooooooooo.',
    '............',
  ],

  'blood': [
    '.....oo.....',
    '....oeeo....',
    '....oeeo....',
    '...oeEEeo...',
    '..oeEEEEeo..',
    '.oeEEEEEEeo.',
    '.oeEEEEEEeo.',
    '.oeEEEEEEeo.',
    '..oeEEEEeo..',
    '..ooeeeeoo..',
    '...oooooo...',
    '............',
  ],
  'bolt': [
    '......ooo...',
    '.....oyyo...',
    '....oyyo....',
    '...oyyo.....',
    '..oyyoooo...',
    '.oyyyyyyo...',
    '.ooooyyyo...',
    '....oyyo....',
    '...oyyo.....',
    '..oyyo......',
    '..oyo.......',
    '..oo........',
  ],
  'horse': [
    '.....ooo....',
    '....o$$$o...',
    '...o$$$$$o..',
    '..o$o$$$$o..',
    '.oo$$$$$$o..',
    'o$$$$$$$$o..',
    'o$$oo$$$$o..',
    'oo..o$$$$o..',
    '....o$$$$o..',
    '...o$$$$$$o.',
    '..o$$$$$$$$o',
    '..oooooooooo',
  ],
  'swords': [
    '.oo......oo.',
    '.oSo....oSo.',
    '..oSo..oSo..',
    '...oSooSo...',
    '....oSSo....',
    '.....oo.....',
    '....oSSo....',
    '...oSooSo...',
    '..oSo..oSo..',
    '.oSo....oSo.',
    '.oGo....oGo.',
    '.oo......oo.',
  ],
  /* Skill cards. */
  'warp': [
    '.....oo.....',
    '....oYYo....',
    '....oYYo....',
    '.o..oYYo..o.',
    '.oYooYYooYo.',
    '.oYYYYYYYYo.',
    '.oYYYYYYYYo.',
    '.oYooYYooYo.',
    '.o..oYYo..o.',
    '....oYYo....',
    '....oYYo....',
    '.....oo.....',
  ],
  'arrows': [
    '...oooooo...',
    '..oBBBBBBo..',
    '.oBBoooo....',
    '.oBBo.......',
    '.oBBo...oo..',
    '.oooo..oBBo.',
    '.oEEo..oBBo.',
    '.oEEo...oo..',
    '.oEEo.......',
    '.oEEoooo....',
    '..oEEEEEEo..',
    '...oooooo...',
  ],
  'sprout': [
    '............',
    '.....oo.....',
    '..oo.oNo....',
    '.oNNooNo....',
    '.oNNNNNo....',
    '..ooNNo.oo..',
    '....oNooNNo.',
    '....oNoNNNo.',
    '....oNooNo..',
    '..ooooNoooo.',
    '.oWWWWWWWWo.',
    '.oooooooooo.',
  ],
  'ice': [
    '.....oo.....',
    '..o..CC..o..',
    '..oC.CC.Co..',
    '...oCCCCo...',
    '.ooCCCCCCoo.',
    '.oCCCCCCCCo.',
    '.oCCCCCCCCo.',
    '.ooCCCCCCoo.',
    '...oCCCCo...',
    '..oC.CC.Co..',
    '..o..CC..o..',
    '.....oo.....',
  ],
  'trap': [
    '.oo......oo.',
    '.oWo....oWo.',
    '.oWWoooooWo.',
    '.oWWWWWWWWo.',
    '..oooooooo..',
    '...oWWWWo...',
    '....oWWo....',
    '...oWWWWo...',
    '..oWWWWWWo..',
    '.oWWWWWWWWo.',
    '.oooooooooo.',
    '............',
  ],
  'crown': [
    '............',
    '.oo......oo.',
    '.oGo.oo.oGo.',
    '.oGooGGooGo.',
    '.oGGGGGGGGo.',
    '.oGGGGGGGGo.',
    '.oGGgGGgGGo.',
    '.oGGGGGGGGo.',
    '.oooooooooo.',
    '..o$$$$$$o..',
    '..o$$$$$$o..',
    '..oooooooo..',
  ],
  'horse-leap': [
    '.....ooo....',
    '....o$$$o...',
    '...o$$$$$o..',
    '..o$o$$$$o..',
    '.oo$$$$$$o..',
    'o$$$$$$$$o..',
    'o$$oo$$$$oyo',
    'oo..o$$$$oyo',
    '....o$$$$oyo',
    '...o$$$$$$oo',
    '..o$$$$$$$oo',
    '..ooooooooo.',
  ],
  'horn': [
    '.o..oo..o...',
    '.oyooyyooyo.',
    '.oyyyyyyyyo.',
    '..oyyyyyyo..',
    '...oooooo...',
    '....o$$o....',
    '...o$$$$o...',
    '..o$$$$$$o..',
    '.o$$$$$$$$o.',
    '.o$$$$$$$$o.',
    '.oooooooooo.',
    '............',
  ],
  /* Stone, not brick. The mock drew this in `R` (a deep red), which is 2.10:1
     against the recessed slot a card sits in — the sprite was a dark shape on a
     dark square. `S` is the sheet's pale tone and clears 10:1 there.
     `art-contrast.test.ts` is what caught it. */
  'wall': [
    '.oooooooooo.',
    '.oSSoSSoSSo.',
    '.oSSoSSoSSo.',
    '.oooooooooo.',
    '.oSoSSoSSoSo',
    '.oSoSSoSSoSo',
    '.oooooooooo.',
    '.oSSoSSoSSo.',
    '.oSSoSSoSSo.',
    '.oooooooooo.',
    '............',
    '............',
  ],
  'chain': [
    '..oooo......',
    '.oSSSSo.....',
    '.oSooSo.....',
    '.oSo.oSo....',
    '.oSSSSo.....',
    '..oooo.oooo.',
    '.......oSSSo',
    '.oooo..oSooS',
    '.oSSSSo.oSSS',
    '.oSooSo.oooo',
    '.oSSSSo.....',
    '..oooo......',
  ],
  'homeward': [
    '.....oo.....',
    '....oRRo....',
    '...oRRRRo...',
    '..oRRRRRRo..',
    '.oRRRRRRRRo.',
    'oRRRRRRRRRRo',
    'ooooRWWRoooo',
    '...oRWWRo...',
    '...oRWWRo...',
    '...oRWWRo...',
    '...oooooo...',
    '............',
  ],
  'fist': [
    '............',
    '.....oo.....',
    '....oyyo....',
    '...oyyyyo...',
    '..oyyyyyyo..',
    '.oyyyyyyyyo.',
    '.ooooyyoooo.',
    '....oyyo....',
    '....oyyo....',
    '....oyyo....',
    '.....oo.....',
    '............',
  ],
  'plus': [
    '.....oo.....',
    '....oNNo....',
    '....oNNo....',
    '.oooooooooo.',
    '.oNNNNNNNNo.',
    '.oNNNNNNNNo.',
    '.oooooooooo.',
    '....oNNo....',
    '....oNNo....',
    '.....oo.....',
    '............',
    '............',
  ],
  'arrow': [
    '.........oo.',
    '........oSo.',
    '......ooSo..',
    '.....oySo...',
    '....oySo....',
    '.oo.oSo.....',
    '.oWooo......',
    '.oWWo.......',
    'oWooWo......',
    'oWo..oWo....',
    '.oo...oWo...',
    '.......oo...',
  ],
  'dagger': [
    '.....oo.....',
    '....oSSo....',
    '....oSSo....',
    '....oSSo....',
    '....oSSo....',
    '.oooSSSooo..',
    '.oGGGGGGGo..',
    '.ooooSooo...',
    '....oSSo....',
    '....oSSo....',
    '....oeeo....',
    '.....oo.....',
  ],
  /* The UI's own furniture — tab bar and the paint palette's eraser. These are
 * never content art ids; nothing in a document may point at them. */
  'nav-play': [
    '.........oo.',
    '........oSo.',
    '.......oSSo.',
    '......oSSo..',
    '.....oSSo...',
    '....oSSo....',
    '...oSSo.....',
    '.oooSo......',
    '.oGGo.......',
    'oGGGGo......',
    '.oo.oGo.....',
    '.....oo.....',
  ],
  'nav-build': [
    '..oo....oo..',
    '.osSo..oSso.',
    '.osSSooSSso.',
    '..osSSSSso..',
    '....oWwo....',
    '....oWwo....',
    '....oWwo....',
    '....oWwo....',
    '....oWwo....',
    '....oWwo....',
    '....oWwo....',
    '.....oo.....',
  ],
  'nav-dex': [
    '............',
    '.oooooooooo.',
    '.oRRRoRRRRo.',
    '.oRrrRoRrRo.',
    '.oRrrRoRrRo.',
    '.oRrrRoRrRo.',
    '.oRrrRoRrRo.',
    '.oRrrRoRrRo.',
    '.oRRRoRRRRo.',
    '.oooooooooo.',
    '............',
    '............',
  ],
  'erase': [
    '.......oooo.',
    '......oSSSSo',
    '.....oSSSSSo',
    '....oSSSSSo.',
    '...oSSSSSo..',
    '..oyyyyyo...',
    '.oyYYYYyo...',
    'oyYYYYyo....',
    'oyYYYyo.....',
    'oyYYyo......',
    'oyyyo.......',
    '.ooo........',
  ],

  /* ---------------------------------------------------------------------------
   * The spare pool and the art for this expansion's own records
   * (PLAN-preset-content-expansion, Phase 3).
   *
   * Produced by `scripts/gen-sprites.ts`, which imports the same gate module
   * `pixels.test.ts` and `art-contrast.test.ts` import — so nothing here entered
   * the sheet without clearing size, palette, blankness, the rect cap, the
   * SHEET-WIDE compression floor and per-surface contrast. Regenerate with:
   *
   *     node --experimental-strip-types scripts/run-spare-sprites.ts --source
   *
   * Each name says what the picture DEPICTS, in one word, because that word is
   * also the art id and an art id may never echo a content id (ADR-004).
   * ------------------------------------------------------------------------- */
  'helm': [
    '............',
    '...oooooo...',
    '..o$$$$$$o..',
    '.o$$$$$$$$o.',
    'o$$$$$$$$$$o',
    'o$oo$$$$oo$o',
    'o$oo$$$$oo$o',
    'o$$$$$$$$$$o',
    '.o$$$$$$$$o.',
    '.o$$$$$$$$o.',
    '..oooooooo..',
    '............',
  ],
  'spear': [
    '.....oo.....',
    '....oSSo....',
    '...oSSSSo...',
    '...oSSSSo...',
    '....oSSo....',
    '.....oo.....',
    '.....$$.....',
    '.....$$.....',
    '.....$$.....',
    '....o$$o....',
    '.....$$.....',
    '.....oo.....',
  ],
  'shield': [
    'oooooooooooo',
    'o$$$$$$$$$$o',
    'o$$$$$$$$$$o',
    'o$$SSSSSS$$o',
    'o$$$$$$$$$$o',
    '.o$$$$$$$$o.',
    '.o$$$$$$$$o.',
    '..o$$$$$$o..',
    '...o$$$$o...',
    '....o$$o....',
    '.....oo.....',
    '............',
  ],
  'cannon': [
    '............',
    '............',
    '..oooooooo..',
    '.oSSSSSSSSo.',
    'oo$$$$$$$$oo',
    'oo$$$$$$$$oo',
    '.oooooooooo.',
    '...o$$$$o...',
    '..o$$$$$$o..',
    '..o$oooo$o..',
    '...oooooo...',
    '............',
  ],
  'banner': [
    '.oo.........',
    '.oooooooo...',
    '.oo$$$$$$o..',
    '.oo$$$$$$$o.',
    '.oo$$$$$$o..',
    '.oooooooo...',
    '.oo.........',
    '.oo.........',
    '.oo.........',
    '.oo.........',
    'oooo........',
    '............',
  ],
  'orb': [
    '............',
    '...oooooo...',
    '..o$$$$$$o..',
    '.o$$SSSS$$o.',
    'o$$$$$$$$$$o',
    'o$$$$$$$$$$o',
    '.o$$$$$$$$o.',
    '..o$$$$$$o..',
    '...oooooo...',
    '....o$$o....',
    '..oooooooo..',
    '............',
  ],
  'axe': [
    '............',
    '..oooooo....',
    '.oSSSSSSo...',
    'oSSSSSSSSo..',
    'oSSSSSS$$o..',
    '.oSSSSo$$o..',
    '..oooo.$$o..',
    '.......$$o..',
    '.......$$o..',
    '.......$$o..',
    '.......ooo..',
    '............',
  ],
  'hammer': [
    '............',
    '..oooooooo..',
    '.oSSSSSSSSo.',
    '.oSSSSSSSSo.',
    '.oooo$$oooo.',
    '.....$$.....',
    '.....$$.....',
    '.....$$.....',
    '.....$$.....',
    '....o$$o....',
    '....oooo....',
    '............',
  ],
  'bow': [
    '...oo.......',
    '..oSSo..o...',
    '.oSSo...o...',
    '.oSSo...o...',
    'oSSo....o...',
    'oSSo....o...',
    'oSSo....o...',
    'oSSo....o...',
    '.oSSo...o...',
    '.oSSo...o...',
    '..oSSo..o...',
    '...oo.......',
  ],
  'staff': [
    '...oooooo...',
    '..o$$$$$$o..',
    '..o$YYYY$o..',
    '..o$$$$$$o..',
    '...oooooo...',
    '....o$$o....',
    '....o$$o....',
    '....o$$o....',
    '....o$$o....',
    '....o$$o....',
    '....o$$o....',
    '....oooo....',
  ],
  'lantern': [
    '....oooo....',
    '...o....o...',
    '..oooooooo..',
    '..o$YYYY$o..',
    '..o$YYYY$o..',
    '..o$YYYY$o..',
    '..o$YYYY$o..',
    '..o$YYYY$o..',
    '..oooooooo..',
    '...oooooo...',
    '............',
    '............',
  ],
  'anvil': [
    '............',
    '...oooooo...',
    '..o$$$$$$o..',
    '.o$$$$$$$$o.',
    '.oo$$$$$$oo.',
    '...o$$$$o...',
    '...o$$$$o...',
    '..o$$$$$$o..',
    '.o$$$$$$$$o.',
    '.oooooooooo.',
    '............',
    '............',
  ],
  'bell': [
    '.....oo.....',
    '....o$$o....',
    '...o$$$$o...',
    '..o$$$$$$o..',
    '..o$$$$$$o..',
    '.o$$$$$$$$o.',
    '.o$$$$$$$$o.',
    'o$$$$$$$$$$o',
    'oooooooooooo',
    '.....oo.....',
    '....oooo....',
    '............',
  ],
  'chalice': [
    'oooooooooooo',
    'o$$$$$$$$$$o',
    'o$$$$$$$$$$o',
    '.o$$$$$$$$o.',
    '..o$$$$$$o..',
    '...o$$$$o...',
    '....o$$o....',
    '....o$$o....',
    '....o$$o....',
    '...o$$$$o...',
    '..oooooooo..',
    '............',
  ],
  'urn': [
    '..oooooooo..',
    '..o$$$$$$o..',
    '.o$$$$$$$$o.',
    'o$$$$$$$$$$o',
    'o$$$rrrr$$$o',
    'o$$$$$$$$$$o',
    'o$$$$$$$$$$o',
    '.o$$$$$$$$o.',
    '..o$$$$$$o..',
    '..oooooooo..',
    '............',
    '............',
  ],
  'gate': [
    'oooooooooooo',
    'o$$$$$$$$$$o',
    'o$oooooooo$o',
    'o$o......o$o',
    'o$o......o$o',
    'o$o......o$o',
    'o$o......o$o',
    'o$o......o$o',
    'o$o......o$o',
    'o$o......o$o',
    'o$o......o$o',
    'ooo......ooo',
  ],
  'obelisk': [
    '.....oo.....',
    '....o$$o....',
    '....o$$o....',
    '...o$$$$o...',
    '...o$$$$o...',
    '...o$$$$o...',
    '..o$$$$$$o..',
    '..o$$$$$$o..',
    '..o$$$$$$o..',
    '.o$$$$$$$$o.',
    'oooooooooooo',
    '............',
  ],
  'wheel': [
    '...oooooo...',
    '.oo$$$$$$oo.',
    'o$$$oooo$$$o',
    'o$$o....o$$o',
    'o$$o....o$$o',
    'o$$oooooo$$o',
    'o$$oooooo$$o',
    'o$$o....o$$o',
    'o$$o....o$$o',
    'o$$$oooo$$$o',
    '.oo$$$$$$oo.',
    '...oooooo...',
  ],
  'talon': [
    '..oo........',
    '.o$$o.......',
    '.o$$$o......',
    '..o$$$o.....',
    '...o$$$o....',
    '....o$$$o...',
    '.....o$$$o..',
    '......o$$$o.',
    '.......o$$o.',
    '........ooo.',
    '............',
    '............',
  ],
  'fang': [
    '.oooo..oooo.',
    '.o$$o..o$$o.',
    '.o$$o..o$$o.',
    '.o$$o..o$$o.',
    '..o$o..o$o..',
    '..o$o..o$o..',
    '..o$o..o$o..',
    '...oo..oo...',
    '............',
    '............',
    '............',
    '............',
  ],
  'pit': [
    '............',
    '..oooooooo..',
    '.oKKKKKKKKo.',
    'oKKKKKKKKKKo',
    'oKKKKKKKKKKo',
    'oKKKKKKKKKKo',
    'oKKKKKKKKKKo',
    'oKKKKKKKKKKo',
    '.oKKKKKKKKo.',
    '..oooooooo..',
    '............',
    '............',
  ],
  'spikes': [
    '............',
    '............',
    '..o..o..o...',
    '.oSo.oSo.oSo',
    '.oSo.oSo.oSo',
    'oSSSoSSSoSSS',
    'oSSSSSSSSSSS',
    'oooooooooooo',
    '............',
    '............',
    '............',
    '............',
  ],
  'water': [
    '............',
    '..oooooooo..',
    '.oCCCCCCCCo.',
    '..oooooooo..',
    '............',
    '..oooooooo..',
    '.oCCCCCCCCo.',
    '..oooooooo..',
    '............',
    '..oooooooo..',
    '.oCCCCCCCCo.',
    '..oooooooo..',
  ],
  'brambles': [
    'oo........oo',
    'onno....onno',
    '.onno..onno.',
    '..onnoonno..',
    '...onnnnoo..',
    '....onno....',
    '....onno....',
    '...onnnnoo..',
    '..onnoonno..',
    '.onno..onno.',
    'onno....onno',
    'oo........oo',
  ],
  'rune': [
    '............',
    '.oooooooooo.',
    '.oggggggggo.',
    '.oggooooggo.',
    '.ogoo..oogo.',
    '.ogo....ogo.',
    '.ogo....ogo.',
    '.ogoo..oogo.',
    '.oggooooggo.',
    '.oggggggggo.',
    '.oooooooooo.',
    '............',
  ],
  'ember': [
    '............',
    '.....oo.....',
    '....oeeo....',
    '...oeEEeo...',
    '..oeEEEEeo..',
    '..oeEEEEeo..',
    '..oeEEEEeo..',
    '...oeeeeo...',
    '....oooo....',
    '............',
    '............',
    '............',
  ],
  'vine': [
    '..oo........',
    '.onno.......',
    '.onno.......',
    '..onno......',
    '...onno.....',
    '....onno....',
    '.....onno...',
    '......onno..',
    '.......onno.',
    '.......onno.',
    '........oo..',
    '............',
  ],
  'crack': [
    '.....oo.....',
    '.....oKo....',
    '....oKo.....',
    '....oKo.....',
    '...oKo......',
    '...oKKo.....',
    '....oKKo....',
    '.....oKKo...',
    '.....oKo....',
    '....oKo.....',
    '....oo......',
    '............',
  ],
  'moss': [
    '............',
    '..oo..oo....',
    '.onno.onno..',
    '.onnooonno..',
    '..onnnnno...',
    '...onnno....',
    '.onnnnnnno..',
    'onnnnnnnnno.',
    '.ooooooooo..',
    '............',
    '............',
    '............',
  ],
  'dune': [
    '............',
    '............',
    '............',
    '.......oo...',
    '.....ooWWo..',
    '...ooWWWWWo.',
    '.ooWWWWWWWWo',
    'oWWWWWWWWWWo',
    'oWWWWWWWWWWo',
    'oooooooooooo',
    '............',
    '............',
  ],
  'reed': [
    '............',
    '.....oo.....',
    '....oN......',
    '....oN......',
    '...oNN......',
    '...oN.......',
    '..oNN.......',
    '..oN........',
    '.oNN........',
    '.oN.........',
    'ooooooooooo.',
    '............',
  ],
  'ash': [
    '............',
    '....oooo....',
    '...oSSSSo...',
    '..oSSSSSSo..',
    '.oSSSSSSSSo.',
    '.oSSSSSSSSo.',
    '..oSSSSSSo..',
    '...oSSSSo...',
    '....oooo....',
    '............',
    '............',
    '............',
  ],
  'clay': [
    '............',
    '............',
    '....oooo....',
    '..ooWWWWoo..',
    '.oWWWWWWWWo.',
    'oWWWWWWWWWWo',
    'oWWWWWWWWWWo',
    '.oWWWWWWWWo.',
    '..oWWWWWWo..',
    '...oooooo...',
    '............',
    '............',
  ],
  'crystal': [
    '.....oo.....',
    '....oCCo....',
    '...oCCCCo...',
    '..oCCCCCCo..',
    '.oCCCCCCCCo.',
    '.oCCCCCCCCo.',
    '..oCCCCCCo..',
    '...oCCCCo...',
    '....oCCo....',
    '.....oo.....',
    '............',
    '............',
  ],
  'fog': [
    '............',
    '..oooooooo..',
    '.oBBBBBBBBo.',
    'oBBBBBBBBBBo',
    '.oBBBBBBBBo.',
    '..oooooooo..',
    '............',
    '....oooo....',
    '...oBBBBo...',
    '....oooo....',
    '............',
    '............',
  ],
  'cairn': [
    '............',
    '.....oo.....',
    '....oDDo....',
    '...oDDDDo...',
    '..oDDDDDDo..',
    '.oDDDDDDDDo.',
    '.oDDDDDDDDo.',
    '..oooooooo..',
    '............',
    '............',
    '............',
    '............',
  ],
  'comet': [
    '............',
    '......oo....',
    '.....oYYo...',
    '....oYYYYo..',
    '...oYYYYYYo.',
    '..oYYYYYYYYo',
    '...oooooooo.',
    '....oooo....',
    '.....oo.....',
    '............',
    '............',
    '............',
  ],
  'flail': [
    '............',
    '..oooo......',
    '.oWWWWo.....',
    '..oooo......',
    '....o.......',
    '....o.......',
    '....o.......',
    '....o.......',
    '....o.......',
    '...o..o.....',
    '............',
    '............',
  ],
  'ring': [
    '....oooo....',
    '...oYYYYo...',
    '..oYY..YYo..',
    '.oYY....YYo.',
    '.oY......Yo.',
    '.oY......Yo.',
    '.oYY....YYo.',
    '..oYY..YYo..',
    '...oYYYYo...',
    '....oooo....',
    '............',
    '............',
  ],
  'lens': [
    '............',
    '....oooo....',
    '..ooCCCCoo..',
    '.oCCCCCCCCo.',
    'oCCCCCCCCCCo',
    'oCCCCCCCCCCo',
    '.oCCCCCCCCo.',
    '..ooCCCCoo..',
    '....oooo....',
    '............',
    '............',
    '............',
  ],
  'sigil': [
    '.....oo.....',
    '....oYYo....',
    '...oYYYYo...',
    '..oYYYYYYo..',
    '.oYYYYYYYYo.',
    'oYYYYYYYYYYo',
    '.oYYYYYYYYo.',
    '..oYYYYYYo..',
    '...oYYYYo...',
    '....oYYo....',
    '.....oo.....',
    '............',
  ],
  'card-beacon': [
    '.....oo.....',
    '....oYYo....',
    '....oYYo....',
    '....oYYo....',
    '....oYYo....',
    '....oYYo....',
    '....oYYo....',
    '....oYYo....',
    '....oYYo....',
    '...oYYYYo...',
    '..oYYYYYYo..',
    '............',
  ],
  'raven': [
    '............',
    '....oooo....',
    '...oNNNNo...',
    '..oNNNNNNo..',
    '.oNNNNNNNNo.',
    '.oNN..NNNNo.',
    '..oN....No..',
    '...oN..No...',
    '....oooo....',
    '.....oo.....',
    '............',
    '............',
  ],
  'cog': [
    '....oooo....',
    '..ooSSSSoo..',
    '.oSSSSSSSSo.',
    'oSSooSSooSSo',
    'oSSSSSSSSSSo',
    'oSSooSSooSSo',
    '.oSSSSSSSSo.',
    '..ooSSSSoo..',
    '....oooo....',
    '............',
    '............',
    '............',
  ],
  'river': [
    '............',
    '..oooooooo..',
    '.oCCCCCCCCo.',
    '..oooooooo..',
    '............',
    '..oooooooo..',
    '.oCCCCCCCCo.',
    '..oooooooo..',
    '............',
    '..oooooooo..',
    '.oCCCCCCCCo.',
    '..oooooooo..',
  ],
  'camp': [
    '............',
    '.....oo.....',
    '....oGGo....',
    '...oGGGGo...',
    '..oGGGGGGo..',
    '.oGGGGGGGGo.',
    'oGGGGGGGGGGo',
    '....oooo....',
    '....o$$o....',
    '....o$$o....',
    '....oooo....',
    '............',
  ],
  'crownlet': [
    '....oYYo....',
    '...oYYYYo...',
    '..oY.o.Yo...',
    '.oYYYYYYYYo.',
    '.oYYYYYYYYo.',
    '..oYYYYYYo..',
    '...oYYYYo...',
    '....oYYo....',
    '....oooo....',
    '............',
    '............',
    '............',
  ],
  'rose': [
    '.....oo.....',
    '....oRRo....',
    '...oRRRRo...',
    '..oRRRRRRo..',
    '...oRRRRo...',
    '....oRRo....',
    '....o$$o....',
    '...o$$$$o...',
    '..o$$$$$$o..',
    '....oooo....',
    '............',
    '............',
  ],
  'shell': [
    '............',
    '....oooo....',
    '..oSSSSSSo..',
    '.oSSSSSSSSo.',
    'oSSSSSSSSSSo',
    'oSSooooSSSSo',
    '.oSSSSSSSSo.',
    '..oSSSSSSo..',
    '....oooo....',
    '............',
    '............',
    '............',
  ],
  'road': [
    '............',
    '..oooooooo..',
    '.oWWWWWWWWo.',
    '.oW......Wo.',
    '.oW......Wo.',
    '.oW......Wo.',
    '.oW......Wo.',
    '.oW......Wo.',
    '.oWWWWWWWWo.',
    '..oooooooo..',
    '............',
    '............',
  ],
  'tower': [
    '...oooooo...',
    '..oYYYYYYo..',
    '..oYYYoYYo..',
    '..oYYYYYYo..',
    '...oYYYYo...',
    '...oYYYYo...',
    '...oYYYYo...',
    '...oYYYYo...',
    '...oYYYYo...',
    '..oYYYYYYo..',
    '...oooooo...',
    '............',
  ],
  'whistle': [
    '............',
    '.....oooo...',
    '....oCCCCo..',
    '...oCCCCCCo.',
    '..oCCCCCCCCo',
    '..oCCCCCCCCo',
    '...oCCCCCCo.',
    '....oCCCCo..',
    '.....oooo...',
    '.......oo...',
    '......oBBo..',
    '............',
  ],
  'card-token': [
    '............',
    '....oooo....',
    '..oGGGGGGo..',
    '.oGGGGGGGGo.',
    'oGGooGGooGGo',
    'oGGGGGGGGGGo',
    '.oGGGGGGGGo.',
    '..oGGGGGGo..',
    '....oooo....',
    '............',
    '............',
    '............',
  ],
  'eye': [
    '............',
    '............',
    '..oooooooo..',
    '.oSSSSSSSSo.',
    'oSSooooooSSo',
    'oSoBBBBBBoSo',
    'oSoBBBBBBoSo',
    'oSSooooooSSo',
    '.oSSSSSSSSo.',
    '..oooooooo..',
    '............',
    '............',
  ],
  'moon': [
    '...oooooo...',
    '..oSSSSSSo..',
    '.oSSSooSSSo.',
    'oSSSo..oSSSo',
    'oSSo....oSSo',
    'oSSo....oSSo',
    'oSSo....oSSo',
    'oSSo....oSSo',
    'oSSSo..oSSSo',
    '.oSSSooSSSo.',
    '..oSSSSSSo..',
    '...oooooo...',
  ],
  'sun': [
    '..o..oo..o..',
    '...o.oo.o...',
    '....oooo....',
    '.oooYYYYooo.',
    'oYYYYYYYYYYo',
    'oYYYYYYYYYYo',
    'oYYYYYYYYYYo',
    'oYYYYYYYYYYo',
    '.oooYYYYooo.',
    '....oooo....',
    '...o.oo.o...',
    '..o..oo..o..',
  ],
  'star': [
    '.....oo.....',
    '....oYYo....',
    '....oYYo....',
    'ooooYYYYoooo',
    'oYYYYYYYYYYo',
    '.oYYYYYYYYo.',
    '..oYYYYYYo..',
    '.oYYYYYYYYo.',
    'oYYoYYYYoYYo',
    'oYo..oo..oYo',
    'oo........oo',
    '............',
  ],
  'key': [
    '..oooo......',
    '.oSSSSo.....',
    'oSSooSSo....',
    'oSo..oSSo...',
    'oSo...oSSo..',
    'oSSooSSSSSo.',
    '.oSSSSooSSSo',
    '..oooo..oSSo',
    '........oSoo',
    '........oSSo',
    '.........ooo',
    '............',
  ],
  'lock': [
    '............',
    '..oooooooo..',
    '.oSSSooSSSo.',
    'oSSo....oSSo',
    'oSSo....oSSo',
    'oooooooooooo',
    'oSSSSSSSSSSo',
    'oSSSooooSSSo',
    'oSSSooooSSSo',
    'oSSSSSSSSSSo',
    'oooooooooooo',
    '............',
  ],
  'book': [
    '............',
    '.oooooooooo.',
    'oSSSSooSSSSo',
    'oSSSSooSSSSo',
    'oSSSSooSSSSo',
    'oSSSSooSSSSo',
    'oSSSSooSSSSo',
    'oSSSSooSSSSo',
    'oSSSSooSSSSo',
    '.oooooooooo.',
    '............',
    '............',
  ],
  'scroll': [
    '............',
    '.oooooooooo.',
    'oSSSSSSSSSSo',
    'oSoooooooo.o',
    'oSSSSSSSSSSo',
    'oSoooooooo.o',
    'oSSSSSSSSSSo',
    'oSoooooooo.o',
    'oSSSSSSSSSSo',
    '.oooooooooo.',
    '............',
    '............',
  ],
  'hourglass': [
    'oooooooooooo',
    'oSSSSSSSSSSo',
    '.oySSSSSSyo.',
    '..oyySSyyo..',
    '...oyyyyo...',
    '....oyyo....',
    '....oyyo....',
    '...oyyyyo...',
    '..oyySSyyo..',
    '.oySSSSSSyo.',
    'oSSSSSSSSSSo',
    'oooooooooooo',
  ],
  'scales': [
    '.....oo.....',
    '.....oo.....',
    'oooooooooooo',
    'o..o.oo.o..o',
    'o..o.oo.o..o',
    'oSSo.oo.oSSo',
    'oSSo.oo.oSSo',
    '.ooo.oo.ooo.',
    '.....oo.....',
    '..oooooooo..',
    '.oSSSSSSSSo.',
    '.oooooooooo.',
  ],
  'feather': [
    '.........oo.',
    '........oSSo',
    '.......oSSSo',
    '......oSSSo.',
    '.....oSSSo..',
    '....oSSSo...',
    '...oSSSo....',
    '..oSSSo.....',
    '.oSSSo......',
    'oSSSo.......',
    'oSoo........',
    'oo..........',
  ],
  'drum': [
    '............',
    '..oooooooo..',
    '.oSSSSSSSSo.',
    'oSoSSooSSoSo',
    'oSSooSSooSSo',
    'oSoSSooSSoSo',
    'oSSooSSooSSo',
    'oSoSSooSSoSo',
    'oSSSSSSSSSSo',
    '.oSSSSSSSSo.',
    '..oooooooo..',
    '............',
  ],
  'mask': [
    '..oooooooo..',
    '.oSSSSSSSSo.',
    'oSSSSSSSSSSo',
    'oSooSSSSooSo',
    'oSooSSSSooSo',
    'oSSSSSSSSSSo',
    'oSSSSSSSSSSo',
    'oSSSooooSSSo',
    '.oSSSSSSSSo.',
    '..oSSSSSSo..',
    '...oooooo...',
    '............',
  ],
  'mirror': [
    '...oooooo...',
    '..oSSSSSSo..',
    '.oSbbbbbbSo.',
    'oSbbbbbbbbSo',
    'oSbbbbbbbbSo',
    'oSbbbbbbbbSo',
    '.oSbbbbbbSo.',
    '..oSSSSSSo..',
    '...oooooo...',
    '....o$$o....',
    '..oooooooo..',
    '............',
  ],
  'coin': [
    '............',
    '...oooooo...',
    '..oGGGGGGo..',
    '.oGGggggGGo.',
    'oGGggGGggGGo',
    'oGGgGGGGgGGo',
    'oGGgGGGGgGGo',
    'oGGggGGggGGo',
    '.oGGggggGGo.',
    '..oGGGGGGo..',
    '...oooooo...',
    '............',
  ],
  'gem': [
    '............',
    '..oooooooo..',
    '.oCCCCCCCCo.',
    'oCCCCCCCCCCo',
    'oCCCCCCCCCCo',
    '.oCCCCCCCCo.',
    '..oCCCCCCo..',
    '...oCCCCo...',
    '....oCCo....',
    '.....oo.....',
    '............',
    '............',
  ],
  'rope': [
    '..ooo.......',
    '.oWWWo......',
    '.oWWWo......',
    '..oWWWo.....',
    '...oWWWo....',
    '....oWWWo...',
    '.....oWWWo..',
    '......oWWWo.',
    '......oWWWo.',
    '.....oWWWo..',
    '....oWWWo...',
    '....ooo.....',
  ],
  'net': [
    'oooooooooooo',
    'oSSooSSooSSo',
    'oSSooSSooSSo',
    'oooooooooooo',
    'oSSooSSooSSo',
    'oSSooSSooSSo',
    'oooooooooooo',
    'oSSooSSooSSo',
    'oSSooSSooSSo',
    'oooooooooooo',
    '............',
    '............',
  ],
  'torch': [
    '............',
    '.....oo.....',
    '....oeeo....',
    '...oeEEeo...',
    '...oeEEeo...',
    '....oeeo....',
    '.....oo.....',
    '....oWWo....',
    '....oWWo....',
    '....oWWo....',
    '....oooo....',
    '............',
  ],
  'cauldron': [
    '............',
    '..o..oo..o..',
    '...o.oo.o...',
    'oooooooooooo',
    'oSssssssssSo',
    'oSssssssssSo',
    'oSssssssssSo',
    '.oSssssssSo.',
    '..oSssssSo..',
    '...oooooo...',
    '............',
    '............',
  ],
  'potion': [
    '....oooo....',
    '....oSSo....',
    '....oSSo....',
    '...oSSSSo...',
    '..oSSSSSSo..',
    '.oSNNNNNNSo.',
    'oSNNNNNNNNSo',
    'oSNNNNNNNNSo',
    'oSNNNNNNNNSo',
    '.oNNNNNNNNo.',
    '..oooooooo..',
    '............',
  ],
  'seed': [
    '............',
    '............',
    '...oooooo...',
    '..oNNNNNNo..',
    '.oNNNNNNNNo.',
    'oNNNNNNNNNNo',
    'oNNNNNNNNNNo',
    'oNNNNNNNNNNo',
    '.oNNNNNNNNo.',
    '..oNNNNNNo..',
    '...oooooo...',
    '............',
  ],
  'root': [
    '.....oo.....',
    '....oWWo....',
    '....oWWo....',
    '...oWWWWo...',
    '..oWWWWWWo..',
    '.oWWooooWWo.',
    'oWWo....oWWo',
    'oWo......oWo',
    'oWo......oWo',
    'oWo......oWo',
    'ooo......ooo',
    '............',
  ],
  'storm': [
    '..oooooooo..',
    '.oHHHHHHHHo.',
    'oHHHHHHHHHHo',
    '.oooooooooo.',
    '....oYYo....',
    '...oYYo.....',
    '..oYYo......',
    '..oYYYYo....',
    '....oYYo....',
    '.....oYo....',
    '.....oo.....',
    '............',
  ],
  'wave': [
    '............',
    '............',
    '.....oooo...',
    '...ooCCCCo..',
    '..oCCCCCCCo.',
    '.oCCCCCCCCCo',
    'oCCCoooCCCCo',
    'oCCo...oCCCo',
    'oCo.....oCCo',
    'oo.......ooo',
    '............',
    '............',
  ],
  'mountain': [
    '............',
    '............',
    '.....oo.....',
    '....oSSo....',
    '...oSSSSo...',
    '...osooso...',
    '..ossoosso..',
    '.oossoossoo.',
    'oossssssssoo',
    'osssssssssso',
    'oooooooooooo',
    '............',
  ],
  'bridge': [
    '............',
    '............',
    '...oooooo...',
    '..oWWWWWWo..',
    '.oWWooooWWo.',
    'oWWo....oWWo',
    'oWo......oWo',
    'oWo......oWo',
    'oWo......oWo',
    'oWo......oWo',
    'ooo......ooo',
    '............',
  ],
  'ladder': [
    '.oo......oo.',
    '.oo......oo.',
    '.oooooooooo.',
    '.oSo....oSo.',
    '.oooooooooo.',
    '.oSo....oSo.',
    '.oooooooooo.',
    '.oSo....oSo.',
    '.oooooooooo.',
    '.oSo....oSo.',
    '.oo......oo.',
    '............',
  ],
  'compass': [
    '............',
    '..oooooooo..',
    '.oSSSSSSSSo.',
    'oSSSoSSoSSSo',
    'oSSooSSooSSo',
    'oSoeeSSeeoSo',
    'oSoeeSSeeoSo',
    'oSSooSSooSSo',
    'oSSSoSSoSSSo',
    '.oSSSSSSSSo.',
    '..oooooooo..',
    '............',
  ],
  'candle': [
    '.....oo.....',
    '....oyyo....',
    '....oyyo....',
    '.....oo.....',
    '...oooooo...',
    '...oSSSSo...',
    '...oSSSSo...',
    '...oSSSSo...',
    '...oSSSSo...',
    '...oSSSSo...',
    '..oooooooo..',
    '............',
  ],
  'lance': [
    '..........oo',
    '.........oSo',
    '........oSSo',
    '.......oSSo.',
    '......o$$o..',
    '.....o$$o...',
    '....o$$o....',
    '...o$$o.....',
    '..o$$o......',
    '.o$$o.......',
    '.oo.........',
    '............',
  ],
  'crossbow': [
    '............',
    '.oo......oo.',
    'oSSo....oSSo',
    'oSSSo..oSSSo',
    '.oSSSooSSSo.',
    '..oSSSSSSo..',
    '....o$$o....',
    '....o$$o....',
    '....o$$o....',
    '....o$$o....',
    '....oooo....',
    '............',
  ],
  'warhorse': [
    '....oo......',
    '...oyyo.....',
    '..oyyo......',
    '..ooooo.....',
    '.oo$$$$o....',
    'o$$$$$$$o...',
    'o$o$$$$$$o..',
    'o$$$$$$$$o..',
    '.oo$$$$$$o..',
    '...o$$$$$o..',
    '...ooooooo..',
    '............',
  ],
  'watchtower': [
    '..oooooooo..',
    '..o$$$$$$o..',
    '..oooooooo..',
    '...o$$$$o...',
    '...o$$$$o...',
    '...o$$$$o...',
    '..o$$$$$$o..',
    '..o$oooo$o..',
    '..o$oooo$o..',
    '.o$$$$$$$$o.',
    'oooooooooooo',
    '............',
  ],
  'censer': [
    '....oooo....',
    '....o..o....',
    '..oooooooo..',
    '.o$YYYYYY$o.',
    'o$YYYYYYYY$o',
    'o$$$$$$$$$$o',
    '.o$$$$$$$$o.',
    '..o$$$$$$o..',
    '...oooooo...',
    '............',
    '............',
    '............',
  ],
  'cloak': [
    '...oooooo...',
    '..o$$$$$$o..',
    '.o$SS$$SS$o.',
    'o$$$$$$$$$$o',
    'o$$$$$$$$$$o',
    'o$$$$$$$$$$o',
    'o$$$$$$$$$$o',
    'o$$$$$$$$$$o',
    'o$$$$$$$$$$o',
    'o$$$$$$$$$$o',
    'oooooooooooo',
    '............',
  ],
  'geyser': [
    '.....oo.....',
    '....oCCo....',
    '....oCCo....',
    '...oCCCCo...',
    '...oCCCCo...',
    '..oCCCCCCo..',
    '..oCCCCCCo..',
    '.oCCCCCCCCo.',
    'oooooooooooo',
    '............',
    '............',
    '............',
  ],
  'thorns': [
    'oo........oo',
    '.oSo....oSo.',
    '..oSo..oSo..',
    '...oSooSo...',
    '....oSSo....',
    '....oSSo....',
    '...oSooSo...',
    '..oSo..oSo..',
    '.oSo....oSo.',
    'oo........oo',
    '............',
    '............',
  ],
  'mist': [
    '............',
    '..oooooo....',
    '.oSSSSSSo...',
    '..oooooooo..',
    '............',
    '...oooooo...',
    '..oSSSSSSo..',
    '...ooooooo..',
    '............',
    '..oooooo....',
    '.oSSSSSSo...',
    '..oooooo....',
  ],
  'beacon': [
    '.....oo.....',
    '....oYYo....',
    '...oYYYYo...',
    '....oYYo....',
    '.....oo.....',
    '...oooooo...',
    '...oSSSSo...',
    '...oSSSSo...',
    '...oSSSSo...',
    '..oSSSSSSo..',
    'oooooooooooo',
    '............',
  ],
  'tribute': [
    '............',
    '..oooooooo..',
    '.oGGGGGGGGo.',
    '.oGGGGGGGGo.',
    '.oooooooooo.',
    'oSSSSSSSSSSo',
    'oSSSoooSSSSo',
    'oSSSoGoSSSSo',
    'oSSSoooSSSSo',
    'oSSSSSSSSSSo',
    '.oooooooooo.',
    '............',
  ],
  'eclipse': [
    '...oooooo...',
    '..oYYYYYYo..',
    '.oYYooooYYo.',
    'oYYoKKKKoYYo',
    'oYoKKKKKKoYo',
    'oYoKKKKKKoYo',
    'oYoKKKKKKoYo',
    'oYYoKKKKoYYo',
    '.oYYooooYYo.',
    '..oYYYYYYo..',
    '...oooooo...',
    '............',
  ],
  'oath': [
    '............',
    '...oo..oo...',
    '..oSSooSSo..',
    '..oSSooSSo..',
    '.ooSSSSSSo..',
    'oSSSSSSSSo..',
    'oSSSSSSSSo..',
    '.oSSSSSSo...',
    '..oSSSSo....',
    '...oSSo.....',
    '...oooo.....',
    '............',
  ],
  'siege': [
    '............',
    '..oo........',
    '.oSSo.......',
    '.oSSo.......',
    '..oSSo......',
    '...oSSooooo.',
    '....oSSSSSo.',
    '.....ooooo..',
    '..ooo...ooo.',
    '.oSSSo.oSSSo',
    '.oSSSo.oSSSo',
    '..ooo...ooo.',
  ],
  'harvest': [
    '............',
    '..o..oo..o..',
    '.oYo.oYo.oYo',
    '.oYo.oYo.oYo',
    '.oYYooYYooYo',
    '..oYYYYYYYo.',
    '...oYYYYYo..',
    '...oWWWWWo..',
    '...oWWWWWo..',
    '...oWWWWWo..',
    '....ooooo...',
    '............',
  ],
  'leash': [
    '............',
    '..oooooooo..',
    '.oSSSSSSSSo.',
    '.oSooooooSo.',
    '.oSo....oSo.',
    '.oSooooooSo.',
    '.oSSSSSSSSo.',
    '..ooooSSoo..',
    '.....oSSo...',
    '.....oSSo...',
    '.....oooo...',
    '............',
  ],
  'blink': [
    '............',
    '.o........o.',
    '..o..oo..o..',
    '...oSSSSo...',
    '..oSSSSSSo..',
    '.oSSSSSSSSo.',
    '..oSSSSSSo..',
    '...oSSSSo...',
    '..o..oo..o..',
    '.o........o.',
    '............',
    '............',
  ],
  'mend': [
    '............',
    '....oooo....',
    '....oSSo....',
    '....oSSo....',
    '.oooSSSSooo.',
    '.oSSSSSSSSo.',
    '.oSSSSSSSSo.',
    '.oooSSSSooo.',
    '....oSSo....',
    '....oSSo....',
    '....oooo....',
    '............',
  ],
  'quake': [
    '............',
    '............',
    'oooooooooooo',
    'oSSSSSSSSSSo',
    'oSSoooooSSSo',
    'oSo.....oSSo',
    'oo.......oSo',
    '..........oo',
    '............',
    '............',
    '............',
    '............',
  ],
  'veil': [
    '..oooooooo..',
    '.oSSSSSSSSo.',
    'oSSSSSSSSSSo',
    'oSSSSSSSSSSo',
    'oSSSSSSSSSSo',
    'oSSSSSSSSSSo',
    '.oSSSSSSSSo.',
    '.oSSSSSSSSo.',
    '..oSSSSSSo..',
    '..oSSSSSSo..',
    '...oooooo...',
    '............',
  ],
  'dart': [
    '.........oo.',
    '........oSo.',
    '.......oSSo.',
    '......oSSo..',
    '.....oSSo...',
    '....oSSo....',
    '...oSSo.....',
    '..oSSo......',
    '.oSSo.......',
    'ooSo........',
    'oSo.........',
    'oo..........',
  ],
  'tide': [
    '............',
    '............',
    '..oooooooo..',
    '.oCCCCCCCCo.',
    'oCCCCCCCCCCo',
    '.oooooooooo.',
    '..oooooooo..',
    '.oCCCCCCCCo.',
    'oCCCCCCCCCCo',
    '.oooooooooo.',
    '............',
    '............',
  ],
  'brand': [
    '............',
    '..oooooooo..',
    '.oSSSSSSSSo.',
    '.oSSoooSSSo.',
    '.oSo...oSSo.',
    '.oSo...oSSo.',
    '.oSSoooSSSo.',
    '.oSSSSSSSSo.',
    '..oooooooo..',
    '....oWWo....',
    '....oWWo....',
    '....oooo....',
  ],
  'echo': [
    '............',
    '.....oo.....',
    '....oSSo....',
    '...oS..So...',
    '..oS....So..',
    '.oS......So.',
    '.oS......So.',
    '..oS....So..',
    '...oS..So...',
    '....oSSo....',
    '.....oo.....',
    '............',
  ],
} as const satisfies Record<string, PixelSprite>

export type SpriteName = keyof typeof PIXEL_SPRITES

export function isSpriteName(name: string): name is SpriteName {
  return Object.hasOwn(PIXEL_SPRITES, name)
}

/**
 * A horizontal run of identical pixels, in sprite coordinates (0..11).
 *
 * The old renderer merged each row into runs to keep a 6x6 board cheap to
 * repaint. `runsOf` stays available to the legacy generator gates, but no
 * runtime component turns these rows into DOM geometry anymore.
 */
export interface PixelRun {
  readonly x: number
  readonly y: number
  readonly w: number
  /** A palette colour, or null for "the caller's tint" — a `$` cell. */
  readonly fill: string | null
}

const runCache = new Map<PixelSprite, readonly PixelRun[]>()

/**
 * The sprite as merged horizontal runs, memoised per sprite.
 *
 * Keyed on the sprite VALUE rather than on its name so a sprite that never
 * entered `PIXEL_SPRITES` — one an author will eventually draw in the editor —
 * caches on the same path as a bundled one.
 */
export function runsOf(sprite: PixelSprite): readonly PixelRun[] {
  const cached = runCache.get(sprite)
  if (cached) return cached

  const runs: PixelRun[] = []
  sprite.forEach((row, y) => {
    let x = 0
    while (x < row.length) {
      const ch = row[x]!
      let w = 1
      while (row[x + w] === ch) w++
      if (ch !== '.') {
        // Unknown characters render magenta rather than vanishing. A sprite with
        // a typo in it should be impossible to miss in review.
        runs.push({ x, y, w, fill: ch === '$' ? null : (PIXEL_PALETTE[ch] ?? '#ff00ff') })
      }
      x += w
    }
  })

  const frozen = Object.freeze(runs)
  runCache.set(sprite, frozen)
  return frozen
}
