import { ART_ASSETS } from './assets'
import type { ArtEntry } from './resolve'

/**
 * The complete image catalogue used by content and the record editor.
 *
 * The map is intentionally a literal: every art id has an explicit surface
 * and an explicit imported WebP source. Pieces own separate white/black
 * files so side identity survives every background and display size.
 */
export const artRegistry: ReadonlyMap<string, ArtEntry> = new Map<string, ArtEntry>([
  ["art.king", { kind: 'sided', white: ART_ASSETS.piece["king"].white, black: ART_ASSETS.piece["king"].black, surface: 'piece' }],
  ["art.queen", { kind: 'sided', white: ART_ASSETS.piece["queen"].white, black: ART_ASSETS.piece["queen"].black, surface: 'piece' }],
  ["art.rook", { kind: 'sided', white: ART_ASSETS.piece["rook"].white, black: ART_ASSETS.piece["rook"].black, surface: 'piece' }],
  ["art.knight", { kind: 'sided', white: ART_ASSETS.piece["knight"].white, black: ART_ASSETS.piece["knight"].black, surface: 'piece' }],
  ["art.bishop", { kind: 'sided', white: ART_ASSETS.piece["bishop"].white, black: ART_ASSETS.piece["bishop"].black, surface: 'piece' }],
  ["art.pawn", { kind: 'sided', white: ART_ASSETS.piece["pawn"].white, black: ART_ASSETS.piece["pawn"].black, surface: 'piece' }],
  ["art.pawn-plus", { kind: 'sided', white: ART_ASSETS.piece["pawn-plus"].white, black: ART_ASSETS.piece["pawn-plus"].black, surface: 'piece' }],
  ["art.knight-plus", { kind: 'sided', white: ART_ASSETS.piece["knight-plus"].white, black: ART_ASSETS.piece["knight-plus"].black, surface: 'piece' }],
  ["art.bishop-plus", { kind: 'sided', white: ART_ASSETS.piece["bishop-plus"].white, black: ART_ASSETS.piece["bishop-plus"].black, surface: 'piece' }],
  ["art.rook-plus", { kind: 'sided', white: ART_ASSETS.piece["rook-plus"].white, black: ART_ASSETS.piece["rook-plus"].black, surface: 'piece' }],
  ["art.archer", { kind: 'sided', white: ART_ASSETS.piece["archer"].white, black: ART_ASSETS.piece["archer"].black, surface: 'piece' }],
  ["art.bomb", { kind: 'neutral', src: ART_ASSETS.square["bomb"], surface: 'square' }],
  ["art.portal", { kind: 'neutral', src: ART_ASSETS.square["portal"], surface: 'square' }],
  ["art.shrine", { kind: 'neutral', src: ART_ASSETS.square["shrine"], surface: 'square' }],
  ["art.sanctuary", { kind: 'neutral', src: ART_ASSETS.square["sanctuary"], surface: 'square' }],
  ["art.mire", { kind: 'neutral', src: ART_ASSETS.square["mire"], surface: 'square' }],
  ["art.hill", { kind: 'neutral', src: ART_ASSETS.card["hill"], surface: 'card' }],
  ["art.three", { kind: 'neutral', src: ART_ASSETS.card["three"], surface: 'card' }],
  ["art.skull", { kind: 'neutral', src: ART_ASSETS.card["skull"], surface: 'card' }],
  ["art.upgrade", { kind: 'neutral', src: ART_ASSETS.card["upgrade"], surface: 'card' }],
  ["art.crest", { kind: 'neutral', src: ART_ASSETS.card["crest"], surface: 'card' }],
  ["art.flame", { kind: 'neutral', src: ART_ASSETS.card["flame"], surface: 'card' }],
  ["art.ranks", { kind: 'neutral', src: ART_ASSETS.card["ranks"], surface: 'card' }],
  ["art.blood", { kind: 'neutral', src: ART_ASSETS.card["blood"], surface: 'card' }],
  ["art.bolt", { kind: 'neutral', src: ART_ASSETS.card["bolt"], surface: 'card' }],
  ["art.horse", { kind: 'neutral', src: ART_ASSETS.card["horse"], surface: 'card' }],
  ["art.swords", { kind: 'neutral', src: ART_ASSETS.card["swords"], surface: 'card' }],
  ["art.warp", { kind: 'neutral', src: ART_ASSETS.card["warp"], surface: 'card' }],
  ["art.arrows", { kind: 'neutral', src: ART_ASSETS.card["arrows"], surface: 'card' }],
  ["art.sprout", { kind: 'neutral', src: ART_ASSETS.card["sprout"], surface: 'card' }],
  ["art.ice", { kind: 'neutral', src: ART_ASSETS.card["ice"], surface: 'card' }],
  ["art.trap", { kind: 'neutral', src: ART_ASSETS.card["trap"], surface: 'card' }],
  ["art.crown", { kind: 'neutral', src: ART_ASSETS.card["crown"], surface: 'card' }],
  ["art.horse-leap", { kind: 'neutral', src: ART_ASSETS.card["horse-leap"], surface: 'card' }],
  ["art.horn", { kind: 'neutral', src: ART_ASSETS.card["horn"], surface: 'card' }],
  ["art.wall", { kind: 'neutral', src: ART_ASSETS.card["wall"], surface: 'card' }],
  ["art.chain", { kind: 'neutral', src: ART_ASSETS.card["chain"], surface: 'card' }],
  ["art.homeward", { kind: 'neutral', src: ART_ASSETS.card["homeward"], surface: 'card' }],
  ["art.fist", { kind: 'neutral', src: ART_ASSETS.card["fist"], surface: 'card' }],
  ["art.plus", { kind: 'neutral', src: ART_ASSETS.card["plus"], surface: 'card' }],
  ["art.arrow", { kind: 'neutral', src: ART_ASSETS.card["arrow"], surface: 'card' }],
  ["art.dagger", { kind: 'neutral', src: ART_ASSETS.card["dagger"], surface: 'card' }],
  ["art.helm", { kind: 'sided', white: ART_ASSETS.piece["helm"].white, black: ART_ASSETS.piece["helm"].black, surface: 'piece' }],
  ["art.spear", { kind: 'sided', white: ART_ASSETS.piece["spear"].white, black: ART_ASSETS.piece["spear"].black, surface: 'piece' }],
  ["art.shield", { kind: 'sided', white: ART_ASSETS.piece["shield"].white, black: ART_ASSETS.piece["shield"].black, surface: 'piece' }],
  ["art.cannon", { kind: 'sided', white: ART_ASSETS.piece["cannon"].white, black: ART_ASSETS.piece["cannon"].black, surface: 'piece' }],
  ["art.banner", { kind: 'sided', white: ART_ASSETS.piece["banner"].white, black: ART_ASSETS.piece["banner"].black, surface: 'piece' }],
  ["art.orb", { kind: 'sided', white: ART_ASSETS.piece["orb"].white, black: ART_ASSETS.piece["orb"].black, surface: 'piece' }],
  ["art.axe", { kind: 'sided', white: ART_ASSETS.piece["axe"].white, black: ART_ASSETS.piece["axe"].black, surface: 'piece' }],
  ["art.hammer", { kind: 'sided', white: ART_ASSETS.piece["hammer"].white, black: ART_ASSETS.piece["hammer"].black, surface: 'piece' }],
  ["art.bow", { kind: 'sided', white: ART_ASSETS.piece["bow"].white, black: ART_ASSETS.piece["bow"].black, surface: 'piece' }],
  ["art.staff", { kind: 'sided', white: ART_ASSETS.piece["staff"].white, black: ART_ASSETS.piece["staff"].black, surface: 'piece' }],
  ["art.lantern", { kind: 'sided', white: ART_ASSETS.piece["lantern"].white, black: ART_ASSETS.piece["lantern"].black, surface: 'piece' }],
  ["art.anvil", { kind: 'sided', white: ART_ASSETS.piece["anvil"].white, black: ART_ASSETS.piece["anvil"].black, surface: 'piece' }],
  ["art.bell", { kind: 'sided', white: ART_ASSETS.piece["bell"].white, black: ART_ASSETS.piece["bell"].black, surface: 'piece' }],
  ["art.chalice", { kind: 'sided', white: ART_ASSETS.piece["chalice"].white, black: ART_ASSETS.piece["chalice"].black, surface: 'piece' }],
  ["art.urn", { kind: 'sided', white: ART_ASSETS.piece["urn"].white, black: ART_ASSETS.piece["urn"].black, surface: 'piece' }],
  ["art.gate", { kind: 'sided', white: ART_ASSETS.piece["gate"].white, black: ART_ASSETS.piece["gate"].black, surface: 'piece' }],
  ["art.obelisk", { kind: 'sided', white: ART_ASSETS.piece["obelisk"].white, black: ART_ASSETS.piece["obelisk"].black, surface: 'piece' }],
  ["art.wheel", { kind: 'sided', white: ART_ASSETS.piece["wheel"].white, black: ART_ASSETS.piece["wheel"].black, surface: 'piece' }],
  ["art.talon", { kind: 'sided', white: ART_ASSETS.piece["talon"].white, black: ART_ASSETS.piece["talon"].black, surface: 'piece' }],
  ["art.fang", { kind: 'sided', white: ART_ASSETS.piece["fang"].white, black: ART_ASSETS.piece["fang"].black, surface: 'piece' }],
  ["art.pit", { kind: 'neutral', src: ART_ASSETS.square["pit"], surface: 'square' }],
  ["art.spikes", { kind: 'neutral', src: ART_ASSETS.square["spikes"], surface: 'square' }],
  ["art.water", { kind: 'neutral', src: ART_ASSETS.square["water"], surface: 'square' }],
  ["art.brambles", { kind: 'neutral', src: ART_ASSETS.square["brambles"], surface: 'square' }],
  ["art.rune", { kind: 'neutral', src: ART_ASSETS.square["rune"], surface: 'square' }],
  ["art.ember", { kind: 'neutral', src: ART_ASSETS.square["ember"], surface: 'square' }],
  ["art.vine", { kind: 'neutral', src: ART_ASSETS.square["vine"], surface: 'square' }],
  ["art.crack", { kind: 'neutral', src: ART_ASSETS.square["crack"], surface: 'square' }],
  ["art.moss", { kind: 'neutral', src: ART_ASSETS.square["moss"], surface: 'square' }],
  ["art.dune", { kind: 'neutral', src: ART_ASSETS.square["dune"], surface: 'square' }],
  ["art.reed", { kind: 'neutral', src: ART_ASSETS.square["reed"], surface: 'square' }],
  ["art.ash", { kind: 'neutral', src: ART_ASSETS.square["ash"], surface: 'square' }],
  ["art.clay", { kind: 'neutral', src: ART_ASSETS.square["clay"], surface: 'square' }],
  ["art.crystal", { kind: 'neutral', src: ART_ASSETS.square["crystal"], surface: 'square' }],
  ["art.fog", { kind: 'neutral', src: ART_ASSETS.square["fog"], surface: 'square' }],
  ["art.cairn", { kind: 'neutral', src: ART_ASSETS.square["cairn"], surface: 'square' }],
  ["art.comet", { kind: 'neutral', src: ART_ASSETS.card["comet"], surface: 'card' }],
  ["art.flail", { kind: 'neutral', src: ART_ASSETS.card["flail"], surface: 'card' }],
  ["art.ring", { kind: 'neutral', src: ART_ASSETS.card["ring"], surface: 'card' }],
  ["art.lens", { kind: 'neutral', src: ART_ASSETS.card["lens"], surface: 'card' }],
  ["art.sigil", { kind: 'neutral', src: ART_ASSETS.card["sigil"], surface: 'card' }],
  ["art.card-beacon", { kind: 'neutral', src: ART_ASSETS.card["card-beacon"], surface: 'card' }],
  ["art.raven", { kind: 'neutral', src: ART_ASSETS.card["raven"], surface: 'card' }],
  ["art.cog", { kind: 'neutral', src: ART_ASSETS.card["cog"], surface: 'card' }],
  ["art.river", { kind: 'neutral', src: ART_ASSETS.card["river"], surface: 'card' }],
  ["art.camp", { kind: 'neutral', src: ART_ASSETS.card["camp"], surface: 'card' }],
  ["art.crownlet", { kind: 'neutral', src: ART_ASSETS.card["crownlet"], surface: 'card' }],
  ["art.rose", { kind: 'neutral', src: ART_ASSETS.card["rose"], surface: 'card' }],
  ["art.shell", { kind: 'neutral', src: ART_ASSETS.card["shell"], surface: 'card' }],
  ["art.road", { kind: 'neutral', src: ART_ASSETS.card["road"], surface: 'card' }],
  ["art.tower", { kind: 'neutral', src: ART_ASSETS.card["tower"], surface: 'card' }],
  ["art.whistle", { kind: 'neutral', src: ART_ASSETS.card["whistle"], surface: 'card' }],
  ["art.card-token", { kind: 'neutral', src: ART_ASSETS.card["card-token"], surface: 'card' }],
  ["art.eye", { kind: 'neutral', src: ART_ASSETS.card["eye"], surface: 'card' }],
  ["art.moon", { kind: 'neutral', src: ART_ASSETS.card["moon"], surface: 'card' }],
  ["art.sun", { kind: 'neutral', src: ART_ASSETS.card["sun"], surface: 'card' }],
  ["art.star", { kind: 'neutral', src: ART_ASSETS.card["star"], surface: 'card' }],
  ["art.key", { kind: 'neutral', src: ART_ASSETS.card["key"], surface: 'card' }],
  ["art.lock", { kind: 'neutral', src: ART_ASSETS.card["lock"], surface: 'card' }],
  ["art.book", { kind: 'neutral', src: ART_ASSETS.card["book"], surface: 'card' }],
  ["art.scroll", { kind: 'neutral', src: ART_ASSETS.card["scroll"], surface: 'card' }],
  ["art.hourglass", { kind: 'neutral', src: ART_ASSETS.card["hourglass"], surface: 'card' }],
  ["art.scales", { kind: 'neutral', src: ART_ASSETS.card["scales"], surface: 'card' }],
  ["art.feather", { kind: 'neutral', src: ART_ASSETS.card["feather"], surface: 'card' }],
  ["art.drum", { kind: 'neutral', src: ART_ASSETS.card["drum"], surface: 'card' }],
  ["art.mask", { kind: 'neutral', src: ART_ASSETS.card["mask"], surface: 'card' }],
  ["art.mirror", { kind: 'neutral', src: ART_ASSETS.card["mirror"], surface: 'card' }],
  ["art.coin", { kind: 'neutral', src: ART_ASSETS.card["coin"], surface: 'card' }],
  ["art.gem", { kind: 'neutral', src: ART_ASSETS.card["gem"], surface: 'card' }],
  ["art.rope", { kind: 'neutral', src: ART_ASSETS.card["rope"], surface: 'card' }],
  ["art.net", { kind: 'neutral', src: ART_ASSETS.card["net"], surface: 'card' }],
  ["art.torch", { kind: 'neutral', src: ART_ASSETS.card["torch"], surface: 'card' }],
  ["art.cauldron", { kind: 'neutral', src: ART_ASSETS.card["cauldron"], surface: 'card' }],
  ["art.potion", { kind: 'neutral', src: ART_ASSETS.card["potion"], surface: 'card' }],
  ["art.seed", { kind: 'neutral', src: ART_ASSETS.card["seed"], surface: 'card' }],
  ["art.root", { kind: 'neutral', src: ART_ASSETS.card["root"], surface: 'card' }],
  ["art.storm", { kind: 'neutral', src: ART_ASSETS.card["storm"], surface: 'card' }],
  ["art.wave", { kind: 'neutral', src: ART_ASSETS.card["wave"], surface: 'card' }],
  ["art.mountain", { kind: 'neutral', src: ART_ASSETS.card["mountain"], surface: 'card' }],
  ["art.bridge", { kind: 'neutral', src: ART_ASSETS.card["bridge"], surface: 'card' }],
  ["art.ladder", { kind: 'neutral', src: ART_ASSETS.card["ladder"], surface: 'card' }],
  ["art.compass", { kind: 'neutral', src: ART_ASSETS.card["compass"], surface: 'card' }],
  ["art.candle", { kind: 'neutral', src: ART_ASSETS.card["candle"], surface: 'card' }],
  ["art.lance", { kind: 'sided', white: ART_ASSETS.piece["lance"].white, black: ART_ASSETS.piece["lance"].black, surface: 'piece' }],
  ["art.crossbow", { kind: 'sided', white: ART_ASSETS.piece["crossbow"].white, black: ART_ASSETS.piece["crossbow"].black, surface: 'piece' }],
  ["art.warhorse", { kind: 'sided', white: ART_ASSETS.piece["warhorse"].white, black: ART_ASSETS.piece["warhorse"].black, surface: 'piece' }],
  ["art.watchtower", { kind: 'sided', white: ART_ASSETS.piece["watchtower"].white, black: ART_ASSETS.piece["watchtower"].black, surface: 'piece' }],
  ["art.censer", { kind: 'sided', white: ART_ASSETS.piece["censer"].white, black: ART_ASSETS.piece["censer"].black, surface: 'piece' }],
  ["art.cloak", { kind: 'sided', white: ART_ASSETS.piece["cloak"].white, black: ART_ASSETS.piece["cloak"].black, surface: 'piece' }],
  ["art.geyser", { kind: 'neutral', src: ART_ASSETS.square["geyser"], surface: 'square' }],
  ["art.thorns", { kind: 'neutral', src: ART_ASSETS.square["thorns"], surface: 'square' }],
  ["art.mist", { kind: 'neutral', src: ART_ASSETS.square["mist"], surface: 'square' }],
  ["art.springboard", { kind: 'neutral', src: ART_ASSETS.square["springboard"], surface: 'square' }],
  ["art.levy", { kind: 'neutral', src: ART_ASSETS.square["levy"], surface: 'square' }],
  ["art.altar", { kind: 'neutral', src: ART_ASSETS.square["altar"], surface: 'square' }],
  ["art.recoil", { kind: 'neutral', src: ART_ASSETS.card["recoil"], surface: 'card' }],
  ["art.democracy", { kind: 'neutral', src: ART_ASSETS.card["democracy"], surface: 'card' }],
  ["art.beacon", { kind: 'neutral', src: ART_ASSETS.card["beacon"], surface: 'card' }],
  ["art.tribute", { kind: 'neutral', src: ART_ASSETS.card["tribute"], surface: 'card' }],
  ["art.eclipse", { kind: 'neutral', src: ART_ASSETS.card["eclipse"], surface: 'card' }],
  ["art.oath", { kind: 'neutral', src: ART_ASSETS.card["oath"], surface: 'card' }],
  ["art.siege", { kind: 'neutral', src: ART_ASSETS.card["siege"], surface: 'card' }],
  ["art.harvest", { kind: 'neutral', src: ART_ASSETS.card["harvest"], surface: 'card' }],
  ["art.leash", { kind: 'neutral', src: ART_ASSETS.card["leash"], surface: 'card' }],
  ["art.blink", { kind: 'neutral', src: ART_ASSETS.card["blink"], surface: 'card' }],
  ["art.mend", { kind: 'neutral', src: ART_ASSETS.card["mend"], surface: 'card' }],
  ["art.quake", { kind: 'neutral', src: ART_ASSETS.card["quake"], surface: 'card' }],
  ["art.veil", { kind: 'neutral', src: ART_ASSETS.card["veil"], surface: 'card' }],
  ["art.dart", { kind: 'neutral', src: ART_ASSETS.card["dart"], surface: 'card' }],
  ["art.tide", { kind: 'neutral', src: ART_ASSETS.card["tide"], surface: 'card' }],
  ["art.brand", { kind: 'neutral', src: ART_ASSETS.card["brand"], surface: 'card' }],
  ["art.echo", { kind: 'neutral', src: ART_ASSETS.card["echo"], surface: 'card' }],
])
