import { expect, test } from '@playwright/test'

const key = 'chess-craft.progression.v1'
const profile = (sparks: number) => ({ version: 1, sparks, ownedUpgradeIds: [], equipped: {}, nextOfferNonce: 0, recentClaimIds: [] })

test('reveal, compare, practice, choose and reload keep one honest acquisition', async ({ page }, info) => {
  await page.goto('/dex')
  await page.evaluate(({ key, value }) => localStorage.setItem(key, JSON.stringify(value)), { key, value: profile(3) })
  await page.reload()
  await page.getByTestId('progression-reveal').click()
  const storedOffer = await page.evaluate((key) => localStorage.getItem(key), key)
  expect(JSON.parse(storedOffer!).sparks).toBe(0)
  await page.reload()
  const offer = page.getByTestId('progression-offer')
  await expect(offer.locator('.upgrade-card')).toHaveCount(3)
  await expect(offer.locator('img')).toHaveCount(3)
  const card = offer.locator('.upgrade-card').first()
  await card.getByRole('button', { name: '무료로 움직여 보기' }).click()
  await card.locator('[data-added="true"]').first().click()
  await expect(card.getByTestId('practice-feedback')).toContainText('새 이동 발견')
  expect(await page.evaluate((key) => localStorage.getItem(key), key)).toBe(storedOffer)
  await card.scrollIntoViewIfNeeded()
  await page.screenshot({ path: info.outputPath('choice-practice.png') })
  await card.locator('[data-testid^="progression-offer-piece."]').click()
  await expect(page.getByTestId('upgrade-acquired')).toBeVisible()
  const stored = JSON.parse((await page.evaluate((key) => localStorage.getItem(key), key))!)
  expect(stored.sparks).toBe(0)
  expect(stored.ownedUpgradeIds).toHaveLength(1)
  expect(stored.pendingOffer).toBeUndefined()
  await page.reload()
  await expect(page.getByTestId('upgrade-collection-count')).toContainText('1 / 12')
  await expect(page.getByTestId(`upgrade-album-${stored.ownedUpgradeIds[0]}`)).toHaveAttribute('data-owned', 'true')
})

test('small-screen album and keyboard practice keep navigation reachable', async ({ page }, info) => {
  await page.setViewportSize({ width: 360, height: 640 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/dex')
  const album = page.getByTestId('upgrade-album-piece.pawn-plus')
  await album.scrollIntoViewIfNeeded()
  await page.screenshot({ path: info.outputPath('album-mobile.png') })
  await album.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('dialog')).toHaveCount(1)
  const tryButton = page.getByTestId('upgrade-practice-piece.pawn-plus')
  await tryButton.focus()
  await page.keyboard.press('Enter')
  const square = page.getByTestId('practice-square-b3')
  await square.scrollIntoViewIfNeeded()
  const box = await square.boundingBox()
  expect(box!.width).toBeGreaterThanOrEqual(44)
  expect(box!.height).toBeGreaterThanOrEqual(44)
  await square.focus()
  await page.keyboard.press('Enter')
  await expect(square).toHaveAttribute('data-piece', 'piece.pawn-plus')
  await expect(page.getByTestId('practice-feedback')).toContainText('새 이동 발견')
  await page.screenshot({ path: info.outputPath('practice-mobile.png') })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(album).toBeFocused()
  await page.getByTestId('rules-close').click()
  await expect(page.getByTestId('start-match')).toBeVisible()
})

test('unreadable profile still permits free exploration without rewriting storage', async ({ page }) => {
  await page.goto('/dex')
  const future = JSON.stringify({ ...profile(9), version: 99 })
  await page.evaluate(({ key, future }) => localStorage.setItem(key, future), { key, future })
  await page.reload()
  await page.getByTestId('upgrade-album-piece.pawn-plus').click()
  await page.getByTestId('upgrade-practice-piece.pawn-plus').click()
  await page.getByTestId('practice-square-b3').click()
  await expect(page.getByTestId('practice-feedback')).toContainText('새 이동 발견')
  expect(await page.evaluate((key) => localStorage.getItem(key), key)).toBe(future)
  await expect(page.getByTestId('upgrade-acquired')).toHaveCount(0)
})
