import { type Candidate, mirror } from './gen-sprites.ts'

/**
 * The spare pool: pictures the app ships that no record claims yet.
 *
 * Every name says what the picture DEPICTS, in one word, because that word
 * becomes the sprite key and the art id — `art.<one-segment>`, never echoing a
 * content id (ADR-004). A candidate nobody can name in one word does not belong
 * here, which is the whole of the curation rule above the mechanical gates.
 *
 * Symmetric shapes are authored as six columns and mirrored. That halves the
 * authoring and makes the symmetry exact: a hand-drawn near-symmetry reads as a
 * wobble rather than as a decision.
 *
 * `$` cells take the caller's tint, so the piece spares serve both armies from
 * one drawing. Square and card spares are neutral and use the palette directly.
 */

const sym = (name: string, surface: Candidate['surface'], half: string[]): Candidate => ({
  name,
  surface,
  rows: mirror(half),
})

const full = (name: string, surface: Candidate['surface'], rows: string[]): Candidate => ({ name, surface, rows })

/** 20 piece spares. Tinted bodies, dark outline — readable on all three board tones. */
const PIECES: Candidate[] = [
  sym('helm', 'piece', [
    '......',
    '...ooo',
    '..o$$$',
    '.o$$$$',
    'o$$$$$',
    'o$oo$$',
    'o$oo$$',
    'o$$$$$',
    '.o$$$$',
    '.o$$$$',
    '..oooo',
    '......',
  ]),
  sym('spear', 'piece', [
    '.....o',
    '....oS',
    '...oSS',
    '...oSS',
    '....oS',
    '.....o',
    '.....$',
    '.....$',
    '.....$',
    '....o$',
    '.....$',
    '.....o',
  ]),
  sym('shield', 'piece', [
    'oooooo',
    'o$$$$$',
    'o$$$$$',
    'o$$SSS',
    'o$$$$$',
    '.o$$$$',
    '.o$$$$',
    '..o$$$',
    '...o$$',
    '....o$',
    '.....o',
    '......',
  ]),
  full('cannon', 'piece', [
    '............',
    '............',
    '..oooooooo..',
    '.oSSSSSSSSo.',
    'oo$$$$$$$$oo',
    'oo$$$$$$$$oo',
    '.oooooooooo.',
    '...o$$$$o...',
    '..o$$$$$$o..',
    '..o$oooo$o..',
    '...oooooo...',
    '............',
  ]),
  full('banner', 'piece', [
    '.oo.........',
    '.oooooooo...',
    '.oo$$$$$$o..',
    '.oo$$$$$$$o.',
    '.oo$$$$$$o..',
    '.oooooooo...',
    '.oo.........',
    '.oo.........',
    '.oo.........',
    '.oo.........',
    'oooo........',
    '............',
  ]),
  sym('orb', 'piece', [
    '......',
    '...ooo',
    '..o$$$',
    '.o$$SS',
    'o$$$$$',
    'o$$$$$',
    '.o$$$$',
    '..o$$$',
    '...ooo',
    '....o$',
    '..oooo',
    '......',
  ]),
  full('axe', 'piece', [
    '............',
    '..oooooo....',
    '.oSSSSSSo...',
    'oSSSSSSSSo..',
    'oSSSSSS$$o..',
    '.oSSSSo$$o..',
    '..oooo.$$o..',
    '.......$$o..',
    '.......$$o..',
    '.......$$o..',
    '.......ooo..',
    '............',
  ]),
  full('hammer', 'piece', [
    '............',
    '..oooooooo..',
    '.oSSSSSSSSo.',
    '.oSSSSSSSSo.',
    '.oooo$$oooo.',
    '.....$$.....',
    '.....$$.....',
    '.....$$.....',
    '.....$$.....',
    '....o$$o....',
    '....oooo....',
    '............',
  ]),
  full('bow', 'piece', [
    '...oo.......',
    '..oSSo..o...',
    '.oSSo...o...',
    '.oSSo...o...',
    'oSSo....o...',
    'oSSo....o...',
    'oSSo....o...',
    'oSSo....o...',
    '.oSSo...o...',
    '.oSSo...o...',
    '..oSSo..o...',
    '...oo.......',
  ]),
  sym('staff', 'piece', [
    '...ooo',
    '..o$$$',
    '..o$YY',
    '..o$$$',
    '...ooo',
    '....o$',
    '....o$',
    '....o$',
    '....o$',
    '....o$',
    '....o$',
    '....oo',
  ]),
  sym('lantern', 'piece', [
    '....oo',
    '...o..',
    '..oooo',
    '..o$YY',
    '..o$YY',
    '..o$YY',
    '..o$YY',
    '..o$YY',
    '..oooo',
    '...ooo',
    '......',
    '......',
  ]),
  full('anvil', 'piece', [
    '............',
    '...oooooo...',
    '..o$$$$$$o..',
    '.o$$$$$$$$o.',
    '.oo$$$$$$oo.',
    '...o$$$$o...',
    '...o$$$$o...',
    '..o$$$$$$o..',
    '.o$$$$$$$$o.',
    '.oooooooooo.',
    '............',
    '............',
  ]),
  sym('bell', 'piece', [
    '.....o',
    '....o$',
    '...o$$',
    '..o$$$',
    '..o$$$',
    '.o$$$$',
    '.o$$$$',
    'o$$$$$',
    'oooooo',
    '.....o',
    '....oo',
    '......',
  ]),
  sym('chalice', 'piece', [
    'oooooo',
    'o$$$$$',
    'o$$$$$',
    '.o$$$$',
    '..o$$$',
    '...o$$',
    '....o$',
    '....o$',
    '....o$',
    '...o$$',
    '..oooo',
    '......',
  ]),
  sym('urn', 'piece', [
    '..oooo',
    '..o$$$',
    '.o$$$$',
    'o$$$$$',
    'o$$$rr',
    'o$$$$$',
    'o$$$$$',
    '.o$$$$',
    '..o$$$',
    '..oooo',
    '......',
    '......',
  ]),
  sym('gate', 'piece', [
    'oooooo',
    'o$$$$$',
    'o$oooo',
    'o$o...',
    'o$o...',
    'o$o...',
    'o$o...',
    'o$o...',
    'o$o...',
    'o$o...',
    'o$o...',
    'ooo...',
  ]),
  sym('obelisk', 'piece', [
    '.....o',
    '....o$',
    '....o$',
    '...o$$',
    '...o$$',
    '...o$$',
    '..o$$$',
    '..o$$$',
    '..o$$$',
    '.o$$$$',
    'oooooo',
    '......',
  ]),
  sym('wheel', 'piece', [
    '...ooo',
    '.oo$$$',
    'o$$$oo',
    'o$$o..',
    'o$$o..',
    'o$$ooo',
    'o$$ooo',
    'o$$o..',
    'o$$o..',
    'o$$$oo',
    '.oo$$$',
    '...ooo',
  ]),
  full('talon', 'piece', [
    '..oo........',
    '.o$$o.......',
    '.o$$$o......',
    '..o$$$o.....',
    '...o$$$o....',
    '....o$$$o...',
    '.....o$$$o..',
    '......o$$$o.',
    '.......o$$o.',
    '........ooo.',
    '............',
    '............',
  ]),
  full('fang', 'piece', [
    '.oooo..oooo.',
    '.o$$o..o$$o.',
    '.o$$o..o$$o.',
    '.o$$o..o$$o.',
    '..o$o..o$o..',
    '..o$o..o$o..',
    '..o$o..o$o..',
    '...oo..oo...',
    '............',
    '............',
    '............',
    '............',
  ]),
]

/** 10 painted-square spares. Neutral, and only ever drawn on a painted square. */
const SQUARES: Candidate[] = [
  full('pit', 'square', [
    '............',
    '..oooooooo..',
    '.oKKKKKKKKo.',
    'oKKKKKKKKKKo',
    'oKKKKKKKKKKo',
    'oKKKKKKKKKKo',
    'oKKKKKKKKKKo',
    'oKKKKKKKKKKo',
    '.oKKKKKKKKo.',
    '..oooooooo..',
    '............',
    '............',
  ]),
  full('spikes', 'square', [
    '............',
    '............',
    '..o..o..o...',
    '.oSo.oSo.oSo',
    '.oSo.oSo.oSo',
    'oSSSoSSSoSSS',
    'oSSSSSSSSSSS',
    'oooooooooooo',
    '............',
    '............',
    '............',
    '............',
  ]),
  full('water', 'square', [
    '............',
    '..oooooooo..',
    '.oCCCCCCCCo.',
    '..oooooooo..',
    '............',
    '..oooooooo..',
    '.oCCCCCCCCo.',
    '..oooooooo..',
    '............',
    '..oooooooo..',
    '.oCCCCCCCCo.',
    '..oooooooo..',
  ]),
  full('brambles', 'square', [
    'oo........oo',
    'onno....onno',
    '.onno..onno.',
    '..onnoonno..',
    '...onnnnoo..',
    '....onno....',
    '....onno....',
    '...onnnnoo..',
    '..onnoonno..',
    '.onno..onno.',
    'onno....onno',
    'oo........oo',
  ]),
  full('rune', 'square', [
    '............',
    '.oooooooooo.',
    '.oggggggggo.',
    '.oggooooggo.',
    '.ogoo..oogo.',
    '.ogo....ogo.',
    '.ogo....ogo.',
    '.ogoo..oogo.',
    '.oggooooggo.',
    '.oggggggggo.',
    '.oooooooooo.',
    '............',
  ]),
  full('ember', 'square', [
    '............',
    '.....oo.....',
    '....oeeo....',
    '...oeEEeo...',
    '..oeEEEEeo..',
    '..oeEEEEeo..',
    '..oeEEEEeo..',
    '...oeeeeo...',
    '....oooo....',
    '............',
    '............',
    '............',
  ]),
  full('vine', 'square', [
    '..oo........',
    '.onno.......',
    '.onno.......',
    '..onno......',
    '...onno.....',
    '....onno....',
    '.....onno...',
    '......onno..',
    '.......onno.',
    '.......onno.',
    '........oo..',
    '............',
  ]),
  full('crack', 'square', [
    '.....oo.....',
    '.....oKo....',
    '....oKo.....',
    '....oKo.....',
    '...oKo......',
    '...oKKo.....',
    '....oKKo....',
    '.....oKKo...',
    '.....oKo....',
    '....oKo.....',
    '....oo......',
    '............',
  ]),
  full('moss', 'square', [
    '............',
    '..oo..oo....',
    '.onno.onno..',
    '.onnooonno..',
    '..onnnnno...',
    '...onnno....',
    '.onnnnnnno..',
    'onnnnnnnnno.',
    '.ooooooooo..',
    '............',
    '............',
    '............',
  ]),
  full('dune', 'square', [
    '............',
    '............',
    '............',
    '.......oo...',
    '.....ooWWo..',
    '...ooWWWWWo.',
    '.ooWWWWWWWWo',
    'oWWWWWWWWWWo',
    'oWWWWWWWWWWo',
    'oooooooooooo',
    '............',
    '............',
  ]),
]

/**
 * 30 card-face spares.
 *
 * A card face lands on a recessed slot, a raised panel and a warm note tile —
 * three backgrounds spanning nearly the whole lightness range. So every one of
 * these carries a LIGHT tone somewhere: an all-dark drawing reads on two of the
 * three and vanishes on the third.
 */
const CARDS: Candidate[] = [
  sym('eye', 'card', [
    '......',
    '......',
    '..oooo',
    '.oSSSS',
    'oSSooo',
    'oSoBBB',
    'oSoBBB',
    'oSSooo',
    '.oSSSS',
    '..oooo',
    '......',
    '......',
  ]),
  sym('moon', 'card', [
    '...ooo',
    '..oSSS',
    '.oSSSo',
    'oSSSo.',
    'oSSo..',
    'oSSo..',
    'oSSo..',
    'oSSo..',
    'oSSSo.',
    '.oSSSo',
    '..oSSS',
    '...ooo',
  ]),
  sym('sun', 'card', [
    '..o..o',
    '...o.o',
    '....oo',
    '.oooYY',
    'oYYYYY',
    'oYYYYY',
    'oYYYYY',
    'oYYYYY',
    '.oooYY',
    '....oo',
    '...o.o',
    '..o..o',
  ]),
  sym('star', 'card', [
    '.....o',
    '....oY',
    '....oY',
    'ooooYY',
    'oYYYYY',
    '.oYYYY',
    '..oYYY',
    '.oYYYY',
    'oYYoYY',
    'oYo..o',
    'oo....',
    '......',
  ]),
  full('key', 'card', [
    '..oooo......',
    '.oSSSSo.....',
    'oSSooSSo....',
    'oSo..oSSo...',
    'oSo...oSSo..',
    'oSSooSSSSSo.',
    '.oSSSSooSSSo',
    '..oooo..oSSo',
    '........oSoo',
    '........oSSo',
    '.........ooo',
    '............',
  ]),
  sym('lock', 'card', [
    '......',
    '..oooo',
    '.oSSSo',
    'oSSo..',
    'oSSo..',
    'oooooo',
    'oSSSSS',
    'oSSSoo',
    'oSSSoo',
    'oSSSSS',
    'oooooo',
    '......',
  ]),
  full('book', 'card', [
    '............',
    '.oooooooooo.',
    'oSSSSooSSSSo',
    'oSSSSooSSSSo',
    'oSSSSooSSSSo',
    'oSSSSooSSSSo',
    'oSSSSooSSSSo',
    'oSSSSooSSSSo',
    'oSSSSooSSSSo',
    '.oooooooooo.',
    '............',
    '............',
  ]),
  full('scroll', 'card', [
    '............',
    '.oooooooooo.',
    'oSSSSSSSSSSo',
    'oSoooooooo.o',
    'oSSSSSSSSSSo',
    'oSoooooooo.o',
    'oSSSSSSSSSSo',
    'oSoooooooo.o',
    'oSSSSSSSSSSo',
    '.oooooooooo.',
    '............',
    '............',
  ]),
  sym('hourglass', 'card', [
    'oooooo',
    'oSSSSS',
    '.oySSS',
    '..oyyS',
    '...oyy',
    '....oy',
    '....oy',
    '...oyy',
    '..oyyS',
    '.oySSS',
    'oSSSSS',
    'oooooo',
  ]),
  sym('scales', 'card', [
    '.....o',
    '.....o',
    'oooooo',
    'o..o.o',
    'o..o.o',
    'oSSo.o',
    'oSSo.o',
    '.ooo.o',
    '.....o',
    '..oooo',
    '.oSSSS',
    '.ooooo',
  ]),
  full('feather', 'card', [
    '.........oo.',
    '........oSSo',
    '.......oSSSo',
    '......oSSSo.',
    '.....oSSSo..',
    '....oSSSo...',
    '...oSSSo....',
    '..oSSSo.....',
    '.oSSSo......',
    'oSSSo.......',
    'oSoo........',
    'oo..........',
  ]),
  sym('drum', 'card', [
    '......',
    '..oooo',
    '.oSSSS',
    'oSoSSo',
    'oSSooS',
    'oSoSSo',
    'oSSooS',
    'oSoSSo',
    'oSSSSS',
    '.oSSSS',
    '..oooo',
    '......',
  ]),
  sym('mask', 'card', [
    '..oooo',
    '.oSSSS',
    'oSSSSS',
    'oSooSS',
    'oSooSS',
    'oSSSSS',
    'oSSSSS',
    'oSSSoo',
    '.oSSSS',
    '..oSSS',
    '...ooo',
    '......',
  ]),
  sym('mirror', 'card', [
    '...ooo',
    '..oSSS',
    '.oSbbb',
    'oSbbbb',
    'oSbbbb',
    'oSbbbb',
    '.oSbbb',
    '..oSSS',
    '...ooo',
    '....o$',
    '..oooo',
    '......',
  ]),
  sym('coin', 'card', [
    '......',
    '...ooo',
    '..oGGG',
    '.oGGgg',
    'oGGggG',
    'oGGgGG',
    'oGGgGG',
    'oGGggG',
    '.oGGgg',
    '..oGGG',
    '...ooo',
    '......',
  ]),
  sym('gem', 'card', [
    '......',
    '..oooo',
    '.oCCCC',
    'oCCCCC',
    'oCCCCC',
    '.oCCCC',
    '..oCCC',
    '...oCC',
    '....oC',
    '.....o',
    '......',
    '......',
  ]),
  full('rope', 'card', [
    '..ooo.......',
    '.oWWWo......',
    '.oWWWo......',
    '..oWWWo.....',
    '...oWWWo....',
    '....oWWWo...',
    '.....oWWWo..',
    '......oWWWo.',
    '......oWWWo.',
    '.....oWWWo..',
    '....oWWWo...',
    '....ooo.....',
  ]),
  full('net', 'card', [
    'oooooooooooo',
    'oSSooSSooSSo',
    'oSSooSSooSSo',
    'oooooooooooo',
    'oSSooSSooSSo',
    'oSSooSSooSSo',
    'oooooooooooo',
    'oSSooSSooSSo',
    'oSSooSSooSSo',
    'oooooooooooo',
    '............',
    '............',
  ]),
  sym('torch', 'card', [
    '......',
    '.....o',
    '....oe',
    '...oeE',
    '...oeE',
    '....oe',
    '.....o',
    '....oW',
    '....oW',
    '....oW',
    '....oo',
    '......',
  ]),
  sym('cauldron', 'card', [
    '......',
    '..o..o',
    '...o.o',
    'oooooo',
    'oSssss',
    'oSssss',
    'oSssss',
    '.oSsss',
    '..oSss',
    '...ooo',
    '......',
    '......',
  ]),
  sym('potion', 'card', [
    '....oo',
    '....oS',
    '....oS',
    '...oSS',
    '..oSSS',
    '.oSNNN',
    'oSNNNN',
    'oSNNNN',
    'oSNNNN',
    '.oNNNN',
    '..oooo',
    '......',
  ]),
  sym('seed', 'card', [
    '......',
    '......',
    '...ooo',
    '..oNNN',
    '.oNNNN',
    'oNNNNN',
    'oNNNNN',
    'oNNNNN',
    '.oNNNN',
    '..oNNN',
    '...ooo',
    '......',
  ]),
  sym('root', 'card', [
    '.....o',
    '....oW',
    '....oW',
    '...oWW',
    '..oWWW',
    '.oWWoo',
    'oWWo..',
    'oWo...',
    'oWo...',
    'oWo...',
    'ooo...',
    '......',
  ]),
  full('storm', 'card', [
    '..oooooooo..',
    '.oHHHHHHHHo.',
    'oHHHHHHHHHHo',
    '.oooooooooo.',
    '....oYYo....',
    '...oYYo.....',
    '..oYYo......',
    '..oYYYYo....',
    '....oYYo....',
    '.....oYo....',
    '.....oo.....',
    '............',
  ]),
  full('wave', 'card', [
    '............',
    '............',
    '.....oooo...',
    '...ooCCCCo..',
    '..oCCCCCCCo.',
    '.oCCCCCCCCCo',
    'oCCCoooCCCCo',
    'oCCo...oCCCo',
    'oCo.....oCCo',
    'oo.......ooo',
    '............',
    '............',
  ]),
  sym('mountain', 'card', [
    '......',
    '......',
    '.....o',
    '....oS',
    '...oSS',
    '...oso',
    '..osso',
    '.oosso',
    'oossss',
    'osssss',
    'oooooo',
    '......',
  ]),
  full('bridge', 'card', [
    '............',
    '............',
    '...oooooo...',
    '..oWWWWWWo..',
    '.oWWooooWWo.',
    'oWWo....oWWo',
    'oWo......oWo',
    'oWo......oWo',
    'oWo......oWo',
    'oWo......oWo',
    'ooo......ooo',
    '............',
  ]),
  full('ladder', 'card', [
    '.oo......oo.',
    '.oo......oo.',
    '.oooooooooo.',
    '.oSo....oSo.',
    '.oooooooooo.',
    '.oSo....oSo.',
    '.oooooooooo.',
    '.oSo....oSo.',
    '.oooooooooo.',
    '.oSo....oSo.',
    '.oo......oo.',
    '............',
  ]),
  sym('compass', 'card', [
    '......',
    '..oooo',
    '.oSSSS',
    'oSSSoS',
    'oSSooS',
    'oSoeeS',
    'oSoeeS',
    'oSSooS',
    'oSSSoS',
    '.oSSSS',
    '..oooo',
    '......',
  ]),
  sym('candle', 'card', [
    '.....o',
    '....oy',
    '....oy',
    '.....o',
    '...ooo',
    '...oSS',
    '...oSS',
    '...oSS',
    '...oSS',
    '...oSS',
    '..oooo',
    '......',
  ]),
]

export const SPARES: Candidate[] = [...PIECES, ...SQUARES, ...CARDS]

/**
 * Art for the records this task ADDS — deliberately not part of the spare pool.
 *
 * Without this split the expansion eats its own surplus: 24 new records claim 24
 * pictures, so a 60-sprite pool would leave 36 unclaimed and AC-008's floor of
 * 20 piece / 10 square / 30 card would fail by construction. The pool exists for
 * what an author makes NEXT, so what this task makes has to bring its own.
 */
const RECORD_PIECES: Candidate[] = [
  full('lance', 'piece', [
    '..........oo',
    '.........oSo',
    '........oSSo',
    '.......oSSo.',
    '......o$$o..',
    '.....o$$o...',
    '....o$$o....',
    '...o$$o.....',
    '..o$$o......',
    '.o$$o.......',
    '.oo.........',
    '............',
  ]),
  full('crossbow', 'piece', [
    '............',
    '.oo......oo.',
    'oSSo....oSSo',
    'oSSSo..oSSSo',
    '.oSSSooSSSo.',
    '..oSSSSSSo..',
    '....o$$o....',
    '....o$$o....',
    '....o$$o....',
    '....o$$o....',
    '....oooo....',
    '............',
  ]),
  full('warhorse', 'piece', [
    '....oo......',
    '...oyyo.....',
    '..oyyo......',
    '..ooooo.....',
    '.oo$$$$o....',
    'o$$$$$$$o...',
    'o$o$$$$$$o..',
    'o$$$$$$$$o..',
    '.oo$$$$$$o..',
    '...o$$$$$o..',
    '...ooooooo..',
    '............',
  ]),
  sym('watchtower', 'piece', [
    '..oooo',
    '..o$$$',
    '..oooo',
    '...o$$',
    '...o$$',
    '...o$$',
    '..o$$$',
    '..o$oo',
    '..o$oo',
    '.o$$$$',
    'oooooo',
    '......',
  ]),
  sym('censer', 'piece', [
    '....oo',
    '....o.',
    '..oooo',
    '.o$YYY',
    'o$YYYY',
    'o$$$$$',
    '.o$$$$',
    '..o$$$',
    '...ooo',
    '......',
    '......',
    '......',
  ]),
  sym('cloak', 'piece', [
    '...ooo',
    '..o$$$',
    '.o$SS$',
    'o$$$$$',
    'o$$$$$',
    'o$$$$$',
    'o$$$$$',
    'o$$$$$',
    'o$$$$$',
    'o$$$$$',
    'oooooo',
    '......',
  ]),
]

const RECORD_SQUARES: Candidate[] = [
  full('geyser', 'square', [
    '.....oo.....',
    '....oCCo....',
    '....oCCo....',
    '...oCCCCo...',
    '...oCCCCo...',
    '..oCCCCCCo..',
    '..oCCCCCCo..',
    '.oCCCCCCCCo.',
    'oooooooooooo',
    '............',
    '............',
    '............',
  ]),
  full('thorns', 'square', [
    'oo........oo',
    '.oSo....oSo.',
    '..oSo..oSo..',
    '...oSooSo...',
    '....oSSo....',
    '....oSSo....',
    '...oSooSo...',
    '..oSo..oSo..',
    '.oSo....oSo.',
    'oo........oo',
    '............',
    '............',
  ]),
  full('mist', 'square', [
    '............',
    '..oooooo....',
    '.oSSSSSSo...',
    '..oooooooo..',
    '............',
    '...oooooo...',
    '..oSSSSSSo..',
    '...ooooooo..',
    '............',
    '..oooooo....',
    '.oSSSSSSo...',
    '..oooooo....',
  ]),
]

const RECORD_CARDS: Candidate[] = [
  sym('beacon', 'card', [
    '.....o',
    '....oY',
    '...oYY',
    '....oY',
    '.....o',
    '...ooo',
    '...oSS',
    '...oSS',
    '...oSS',
    '..oSSS',
    'oooooo',
    '......',
  ]),
  full('tribute', 'card', [
    '............',
    '..oooooooo..',
    '.oGGGGGGGGo.',
    '.oGGGGGGGGo.',
    '.oooooooooo.',
    'oSSSSSSSSSSo',
    'oSSSoooSSSSo',
    'oSSSoGoSSSSo',
    'oSSSoooSSSSo',
    'oSSSSSSSSSSo',
    '.oooooooooo.',
    '............',
  ]),
  sym('eclipse', 'card', [
    '...ooo',
    '..oYYY',
    '.oYYoo',
    'oYYoKK',
    'oYoKKK',
    'oYoKKK',
    'oYoKKK',
    'oYYoKK',
    '.oYYoo',
    '..oYYY',
    '...ooo',
    '......',
  ]),
  full('oath', 'card', [
    '............',
    '...oo..oo...',
    '..oSSooSSo..',
    '..oSSooSSo..',
    '.ooSSSSSSo..',
    'oSSSSSSSSo..',
    'oSSSSSSSSo..',
    '.oSSSSSSo...',
    '..oSSSSo....',
    '...oSSo.....',
    '...oooo.....',
    '............',
  ]),
  full('siege', 'card', [
    '............',
    '..oo........',
    '.oSSo.......',
    '.oSSo.......',
    '..oSSo......',
    '...oSSooooo.',
    '....oSSSSSo.',
    '.....ooooo..',
    '..ooo...ooo.',
    '.oSSSo.oSSSo',
    '.oSSSo.oSSSo',
    '..ooo...ooo.',
  ]),
  full('harvest', 'card', [
    '............',
    '..o..oo..o..',
    '.oYo.oYo.oYo',
    '.oYo.oYo.oYo',
    '.oYYooYYooYo',
    '..oYYYYYYYo.',
    '...oYYYYYo..',
    '...oWWWWWo..',
    '...oWWWWWo..',
    '...oWWWWWo..',
    '....ooooo...',
    '............',
  ]),
  full('leash', 'card', [
    '............',
    '..oooooooo..',
    '.oSSSSSSSSo.',
    '.oSooooooSo.',
    '.oSo....oSo.',
    '.oSooooooSo.',
    '.oSSSSSSSSo.',
    '..ooooSSoo..',
    '.....oSSo...',
    '.....oSSo...',
    '.....oooo...',
    '............',
  ]),
  full('blink', 'card', [
    '............',
    '.o........o.',
    '..o..oo..o..',
    '...oSSSSo...',
    '..oSSSSSSo..',
    '.oSSSSSSSSo.',
    '..oSSSSSSo..',
    '...oSSSSo...',
    '..o..oo..o..',
    '.o........o.',
    '............',
    '............',
  ]),
  full('mend', 'card', [
    '............',
    '....oooo....',
    '....oSSo....',
    '....oSSo....',
    '.oooSSSSooo.',
    '.oSSSSSSSSo.',
    '.oSSSSSSSSo.',
    '.oooSSSSooo.',
    '....oSSo....',
    '....oSSo....',
    '....oooo....',
    '............',
  ]),
  full('quake', 'card', [
    '............',
    '............',
    'oooooooooooo',
    'oSSSSSSSSSSo',
    'oSSoooooSSSo',
    'oSo.....oSSo',
    'oo.......oSo',
    '..........oo',
    '............',
    '............',
    '............',
    '............',
  ]),
  sym('veil', 'card', [
    '..oooo',
    '.oSSSS',
    'oSSSSS',
    'oSSSSS',
    'oSSSSS',
    'oSSSSS',
    '.oSSSS',
    '.oSSSS',
    '..oSSS',
    '..oSSS',
    '...ooo',
    '......',
  ]),
  full('dart', 'card', [
    '.........oo.',
    '........oSo.',
    '.......oSSo.',
    '......oSSo..',
    '.....oSSo...',
    '....oSSo....',
    '...oSSo.....',
    '..oSSo......',
    '.oSSo.......',
    'ooSo........',
    'oSo.........',
    'oo..........',
  ]),
  full('tide', 'card', [
    '............',
    '............',
    '..oooooooo..',
    '.oCCCCCCCCo.',
    'oCCCCCCCCCCo',
    '.oooooooooo.',
    '..oooooooo..',
    '.oCCCCCCCCo.',
    'oCCCCCCCCCCo',
    '.oooooooooo.',
    '............',
    '............',
  ]),
  full('brand', 'card', [
    '............',
    '..oooooooo..',
    '.oSSSSSSSSo.',
    '.oSSoooSSSo.',
    '.oSo...oSSo.',
    '.oSo...oSSo.',
    '.oSSoooSSSo.',
    '.oSSSSSSSSo.',
    '..oooooooo..',
    '....oWWo....',
    '....oWWo....',
    '....oooo....',
  ]),
  full('echo', 'card', [
    '............',
    '.....oo.....',
    '....oSSo....',
    '...oS..So...',
    '..oS....So..',
    '.oS......So.',
    '.oS......So.',
    '..oS....So..',
    '...oS..So...',
    '....oSSo....',
    '.....oo.....',
    '............',
  ]),
]

/** The 24 pictures the new records point at. Registered, but never spare. */
export const RECORD_ART: Candidate[] = [...RECORD_PIECES, ...RECORD_SQUARES, ...RECORD_CARDS]
